import type { Template } from '@/types'

export const templates: Template[] = [
  // Seed Packet Templates
  {
    id: 'seed-tomato',
    name: 'Tomato Seeds',
    description: 'Classic seed packet label for tomatoes',
    type: 'seed-packet',
    category: 'Garden',
    defaultSize: '2.25x4',
    defaultData: {
      backgroundColor: '#f8f9fa',
      textElements: [
        {
          id: '1',
          text: 'TOMATO',
          x: 50,
          y: 20,
          fontSize: 24,
          fontWeight: 'bold',
          textAlign: 'center',
          color: '#2d5016',
        },
        {
          id: '2',
          text: 'Variety:',
          x: 10,
          y: 40,
          fontSize: 12,
          fontWeight: 'bold',
          textAlign: 'left',
          color: '#333333',
        },
        {
          id: '3',
          text: 'Planted:',
          x: 10,
          y: 55,
          fontSize: 12,
          fontWeight: 'normal',
          textAlign: 'left',
          color: '#333333',
        },
        {
          id: '4',
          text: 'Notes:',
          x: 10,
          y: 70,
          fontSize: 12,
          fontWeight: 'normal',
          textAlign: 'left',
          color: '#333333',
        },
      ],
      iconElements: [],
    },
  },
  {
    id: 'seed-herbs',
    name: 'Herb Seeds',
    description: 'Label for herb seed packets',
    type: 'seed-packet',
    category: 'Garden',
    defaultSize: '2.25x1.25',
    defaultData: {
      backgroundColor: '#e8f5e9',
      textElements: [
        {
          id: '1',
          text: 'BASIL',
          x: 50,
          y: 40,
          fontSize: 18,
          fontWeight: 'bold',
          textAlign: 'center',
          color: '#1b5e20',
        },
        {
          id: '2',
          text: 'Sow Date:',
          x: 50,
          y: 65,
          fontSize: 10,
          fontWeight: 'normal',
          textAlign: 'center',
          color: '#333333',
        },
      ],
      iconElements: [],
    },
  },
  {
    id: 'seed-vegetable',
    name: 'Vegetable Seeds',
    description: 'General vegetable seed label',
    type: 'seed-packet',
    category: 'Garden',
    defaultSize: '2.25x4',
    defaultData: {
      backgroundColor: '#fff3e0',
      textElements: [
        {
          id: '1',
          text: 'VEGETABLES',
          x: 50,
          y: 15,
          fontSize: 20,
          fontWeight: 'bold',
          textAlign: 'center',
          color: '#e65100',
        },
        {
          id: '2',
          text: 'Type:',
          x: 10,
          y: 35,
          fontSize: 12,
          fontWeight: 'bold',
          textAlign: 'left',
          color: '#333333',
        },
        {
          id: '3',
          text: 'Date:',
          x: 10,
          y: 50,
          fontSize: 12,
          fontWeight: 'normal',
          textAlign: 'left',
          color: '#333333',
        },
      ],
      iconElements: [],
    },
  },

  // Mason Jar Templates
  {
    id: 'mason-jam',
    name: 'Homemade Jam',
    description: 'Label for homemade jams and preserves',
    type: 'mason-jar',
    category: 'Kitchen',
    defaultSize: '3.5x1.125',
    defaultData: {
      backgroundColor: '#fce4ec',
      textElements: [
        {
          id: '1',
          text: 'Strawberry Jam',
          x: 50,
          y: 35,
          fontSize: 16,
          fontWeight: 'bold',
          textAlign: 'center',
          color: '#880e4f',
        },
        {
          id: '2',
          text: 'Made: __/__/__',
          x: 50,
          y: 60,
          fontSize: 10,
          fontWeight: 'normal',
          textAlign: 'center',
          color: '#333333',
        },
      ],
      iconElements: [],
    },
  },
  {
    id: 'mason-pickles',
    name: 'Pickles & Preserves',
    description: 'Label for pickled vegetables',
    type: 'mason-jar',
    category: 'Kitchen',
    defaultSize: '2.25x4',
    defaultData: {
      backgroundColor: '#f1f8e9',
      textElements: [
        {
          id: '1',
          text: 'PICKLES',
          x: 50,
          y: 20,
          fontSize: 22,
          fontWeight: 'bold',
          textAlign: 'center',
          color: '#33691e',
        },
        {
          id: '2',
          text: 'Contents:',
          x: 10,
          y: 40,
          fontSize: 12,
          fontWeight: 'bold',
          textAlign: 'left',
          color: '#333333',
        },
        {
          id: '3',
          text: 'Date:',
          x: 10,
          y: 55,
          fontSize: 12,
          fontWeight: 'normal',
          textAlign: 'left',
          color: '#333333',
        },
      ],
      iconElements: [],
    },
  },
  {
    id: 'mason-sauce',
    name: 'Sauces',
    description: 'Label for homemade sauces',
    type: 'mason-jar',
    category: 'Kitchen',
    defaultSize: '3.5x1.125',
    defaultData: {
      backgroundColor: '#ffebee',
      textElements: [
        {
          id: '1',
          text: 'Tomato Sauce',
          x: 50,
          y: 40,
          fontSize: 16,
          fontWeight: 'bold',
          textAlign: 'center',
          color: '#c62828',
        },
        {
          id: '2',
          text: 'Batch: __/__/__',
          x: 50,
          y: 65,
          fontSize: 10,
          fontWeight: 'normal',
          textAlign: 'center',
          color: '#333333',
        },
      ],
      iconElements: [],
    },
  },

  // Freezer Container Templates
  {
    id: 'freezer-meal',
    name: 'Freezer Meal',
    description: 'Label for frozen meals',
    type: 'freezer',
    category: 'Kitchen',
    defaultSize: '3.5x1.125',
    defaultData: {
      backgroundColor: '#e3f2fd',
      textElements: [
        {
          id: '1',
          text: 'Lasagna',
          x: 50,
          y: 30,
          fontSize: 16,
          fontWeight: 'bold',
          textAlign: 'center',
          color: '#0d47a1',
        },
        {
          id: '2',
          text: 'Frozen:',
          x: 10,
          y: 55,
          fontSize: 10,
          fontWeight: 'normal',
          textAlign: 'left',
          color: '#333333',
        },
        {
          id: '3',
          text: 'Reheat: 350°F, 45 min',
          x: 10,
          y: 70,
          fontSize: 9,
          fontWeight: 'normal',
          textAlign: 'left',
          color: '#333333',
        },
      ],
      iconElements: [],
    },
  },
  {
    id: 'freezer-soup',
    name: 'Soup & Stew',
    description: 'Label for frozen soups',
    type: 'freezer',
    category: 'Kitchen',
    defaultSize: '2.25x4',
    defaultData: {
      backgroundColor: '#fff9c4',
      textElements: [
        {
          id: '1',
          text: 'Chicken Soup',
          x: 50,
          y: 20,
          fontSize: 18,
          fontWeight: 'bold',
          textAlign: 'center',
          color: '#f57f17',
        },
        {
          id: '2',
          text: 'Date Frozen:',
          x: 10,
          y: 40,
          fontSize: 11,
          fontWeight: 'bold',
          textAlign: 'left',
          color: '#333333',
        },
        {
          id: '3',
          text: 'Servings:',
          x: 10,
          y: 55,
          fontSize: 11,
          fontWeight: 'normal',
          textAlign: 'left',
          color: '#333333',
        },
      ],
      iconElements: [],
    },
  },
  {
    id: 'freezer-baked',
    name: 'Baked Goods',
    description: 'Label for frozen baked goods',
    type: 'freezer',
    category: 'Kitchen',
    defaultSize: '2.25x1.25',
    defaultData: {
      backgroundColor: '#fce4ec',
      textElements: [
        {
          id: '1',
          text: 'Cookies',
          x: 50,
          y: 40,
          fontSize: 16,
          fontWeight: 'bold',
          textAlign: 'center',
          color: '#880e4f',
        },
        {
          id: '2',
          text: 'Baked: __/__',
          x: 50,
          y: 65,
          fontSize: 10,
          fontWeight: 'normal',
          textAlign: 'center',
          color: '#333333',
        },
      ],
      iconElements: [],
    },
  },

  // Kids School Supplies Templates
  {
    id: 'school-name',
    name: 'Name Tag',
    description: 'Simple name label for school supplies',
    type: 'kids-school',
    category: 'School',
    defaultSize: '3.5x1.125',
    defaultData: {
      backgroundColor: '#fff9c4',
      textElements: [
        {
          id: '1',
          text: 'Emma Johnson',
          x: 50,
          y: 45,
          fontSize: 18,
          fontWeight: 'bold',
          textAlign: 'center',
          color: '#f57f17',
        },
        {
          id: '2',
          text: 'Grade 3',
          x: 50,
          y: 70,
          fontSize: 12,
          fontWeight: 'normal',
          textAlign: 'center',
          color: '#333333',
        },
      ],
      iconElements: [],
    },
  },
  {
    id: 'school-subject',
    name: 'Subject Label',
    description: 'Label for notebooks and folders',
    type: 'kids-school',
    category: 'School',
    defaultSize: '2.25x4',
    defaultData: {
      backgroundColor: '#e1f5fe',
      textElements: [
        {
          id: '1',
          text: 'MATH',
          x: 50,
          y: 25,
          fontSize: 24,
          fontWeight: 'bold',
          textAlign: 'center',
          color: '#01579b',
        },
        {
          id: '2',
          text: 'Name:',
          x: 10,
          y: 45,
          fontSize: 12,
          fontWeight: 'bold',
          textAlign: 'left',
          color: '#333333',
        },
        {
          id: '3',
          text: 'Grade:',
          x: 10,
          y: 60,
          fontSize: 12,
          fontWeight: 'normal',
          textAlign: 'left',
          color: '#333333',
        },
      ],
      iconElements: [],
    },
  },
  {
    id: 'school-supplies',
    name: 'Supply Labels',
    description: 'Small labels for pencils, crayons, etc',
    type: 'kids-school',
    category: 'School',
    defaultSize: '2.25x1.25',
    defaultData: {
      backgroundColor: '#f3e5f5',
      textElements: [
        {
          id: '1',
          text: 'Alex M.',
          x: 50,
          y: 50,
          fontSize: 14,
          fontWeight: 'bold',
          textAlign: 'center',
          color: '#4a148c',
        },
      ],
      iconElements: [],
    },
  },

  // Pantry Templates
  {
    id: 'pantry-jar',
    name: 'Pantry Jar',
    description: 'Label for pantry storage jars',
    type: 'pantry',
    category: 'Kitchen',
    defaultSize: '3.5x1.125',
    defaultData: {
      backgroundColor: '#ffffff',
      textElements: [
        {
          id: '1',
          text: 'All-Purpose Flour',
          x: 50,
          y: 40,
          fontSize: 16,
          fontWeight: 'bold',
          textAlign: 'center',
          color: '#212121',
        },
        {
          id: '2',
          text: 'Expires: __/__/__',
          x: 50,
          y: 65,
          fontSize: 10,
          fontWeight: 'normal',
          textAlign: 'center',
          color: '#666666',
        },
      ],
      iconElements: [],
    },
  },
  {
    id: 'pantry-spice',
    name: 'Spice Jar',
    description: 'Label for spice containers',
    type: 'pantry',
    category: 'Kitchen',
    defaultSize: '2.25x1.25',
    defaultData: {
      backgroundColor: '#fff8e1',
      textElements: [
        {
          id: '1',
          text: 'BASIL',
          x: 50,
          y: 40,
          fontSize: 14,
          fontWeight: 'bold',
          textAlign: 'center',
          color: '#f57f17',
        },
        {
          id: '2',
          text: 'Best by: __/__',
          x: 50,
          y: 65,
          fontSize: 9,
          fontWeight: 'normal',
          textAlign: 'center',
          color: '#666666',
        },
      ],
      iconElements: [],
    },
  },
  {
    id: 'pantry-container',
    name: 'Storage Container',
    description: 'Label for general pantry containers',
    type: 'pantry',
    category: 'Kitchen',
    defaultSize: '2.25x4',
    defaultData: {
      backgroundColor: '#f5f5f5',
      textElements: [
        {
          id: '1',
          text: 'RICE',
          x: 50,
          y: 20,
          fontSize: 20,
          fontWeight: 'bold',
          textAlign: 'center',
          color: '#424242',
        },
        {
          id: '2',
          text: 'Type:',
          x: 10,
          y: 40,
          fontSize: 12,
          fontWeight: 'bold',
          textAlign: 'left',
          color: '#333333',
        },
        {
          id: '3',
          text: 'Opened:',
          x: 10,
          y: 55,
          fontSize: 12,
          fontWeight: 'normal',
          textAlign: 'left',
          color: '#333333',
        },
      ],
      iconElements: [],
    },
  },
  {
    id: 'pantry-baking',
    name: 'Baking Supplies',
    description: 'Label for baking ingredients',
    type: 'pantry',
    category: 'Kitchen',
    defaultSize: '3.5x1.125',
    defaultData: {
      backgroundColor: '#fce4ec',
      textElements: [
        {
          id: '1',
          text: 'Brown Sugar',
          x: 50,
          y: 40,
          fontSize: 16,
          fontWeight: 'bold',
          textAlign: 'center',
          color: '#880e4f',
        },
        {
          id: '2',
          text: 'Purchase Date: __/__/__',
          x: 50,
          y: 65,
          fontSize: 9,
          fontWeight: 'normal',
          textAlign: 'center',
          color: '#666666',
        },
      ],
      iconElements: [],
    },
  },
]

export function getTemplateById(id: string): Template | undefined {
  return templates.find((t) => t.id === id)
}

export function getTemplatesByCategory(category: string): Template[] {
  return templates.filter((t) => t.category === category)
}

export function getTemplatesByType(type: string): Template[] {
  return templates.filter((t) => t.type === type)
}

export const categories = ['Garden', 'Kitchen', 'School']
