import { Template, createLockedElement, createEditableElement } from './enhanced-types'
import { TextElement, ShapeElement } from '@/types/designer'

// Freezer templates use 4" × 2" size (1200 x 600 pixels)
const CANVAS_WIDTH = 1200
const CANVAS_HEIGHT = 600

export const freezerTemplates: Template[] = [
  // 1. Classic Freezer Label
  {
    metadata: {
      id: 'freezer-classic',
      name: 'Classic Freezer',
      description: 'Traditional freezer label with date and contents fields',
      category: 'freezer',
      size: '4x2',
      tags: ['classic', 'functional', 'organized', 'simple'],
      difficulty: 'beginner',
      lockedElementIds: ['border-main', 'divider-line', 'date-box', 'contents-box'],
      editableElementIds: ['contents-text', 'date-text', 'notes-text'],
    },
    backgroundColor: '#E8F4F8',
    elements: [
      // Main border
      createLockedElement<ShapeElement>({
        id: 'border-main',
        type: 'shape',
        shapeType: 'rectangle',
        x: 20,
        y: 20,
        width: CANVAS_WIDTH - 40,
        height: CANVAS_HEIGHT - 40,
        rotation: 0,
        zIndex: 1,
        fill: 'transparent',
        stroke: '#2C5F7C',
        strokeWidth: 3,
        cornerRadius: 8,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Date box background
      createLockedElement<ShapeElement>({
        id: 'date-box',
        type: 'shape',
        shapeType: 'rectangle',
        x: 840,
        y: 60,
        width: 300,
        height: 120,
        rotation: 0,
        zIndex: 2,
        fill: '#B8D4E3',
        stroke: '#2C5F7C',
        strokeWidth: 2,
        cornerRadius: 6,
        locked: true,
        visible: true,
        opacity: 0.4,
      }),
      // Contents box background
      createLockedElement<ShapeElement>({
        id: 'contents-box',
        type: 'shape',
        shapeType: 'rectangle',
        x: 60,
        y: 60,
        width: 740,
        height: 480,
        rotation: 0,
        zIndex: 2,
        fill: '#FFFFFF',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 6,
        locked: true,
        visible: true,
        opacity: 0.7,
      }),
      // Divider line
      createLockedElement<ShapeElement>({
        id: 'divider-line',
        type: 'shape',
        shapeType: 'rectangle',
        x: 820,
        y: 60,
        width: 2,
        height: 480,
        rotation: 0,
        zIndex: 3,
        fill: '#2C5F7C',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 0.3,
      }),
      // Editable contents text
      createEditableElement<TextElement>({
        id: 'contents-text',
        type: 'text',
        content: 'Chicken Breast\n(4 pieces)',
        x: 430,
        y: 230,
        width: 650,
        height: 140,
        rotation: 0,
        zIndex: 10,
        fontSize: 56,
        fontFamily: 'Poppins',
        fontWeight: 600,
        color: '#1A3D52',
        textAlign: 'center',
        lineHeight: 1.3,
        letterSpacing: 0,
        locked: false,
        visible: true,
        opacity: 1,
      }),
      // Editable date text
      createEditableElement<TextElement>({
        id: 'date-text',
        type: 'text',
        content: 'Nov 11\n2025',
        x: 990,
        y: 90,
        width: 250,
        height: 80,
        rotation: 0,
        zIndex: 10,
        fontSize: 36,
        fontFamily: 'Inter',
        fontWeight: 700,
        color: '#2C5F7C',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 0,
        locked: false,
        visible: true,
        opacity: 1,
      }),
      // Editable notes text
      createEditableElement<TextElement>({
        id: 'notes-text',
        type: 'text',
        content: 'Use by: Feb 2026',
        x: 990,
        y: 420,
        width: 280,
        height: 40,
        rotation: 0,
        zIndex: 10,
        fontSize: 20,
        fontFamily: 'Inter',
        fontWeight: 400,
        color: '#5A7F95',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 0,
        locked: false,
        visible: true,
        opacity: 1,
      }),
    ],
  },

  // 2. Modern Freezer Label
  {
    metadata: {
      id: 'freezer-modern',
      name: 'Modern Freezer',
      description: 'Clean modern design with color accent',
      category: 'freezer',
      size: '4x2',
      tags: ['modern', 'clean', 'colorful', 'organized'],
      difficulty: 'beginner',
      lockedElementIds: ['accent-bar', 'grid-bg', 'icon-circle'],
      editableElementIds: ['item-text', 'date-label'],
    },
    backgroundColor: '#FFFFFF',
    elements: [
      // Accent color bar
      createLockedElement<ShapeElement>({
        id: 'accent-bar',
        type: 'shape',
        shapeType: 'rectangle',
        x: 0,
        y: 0,
        width: 180,
        height: CANVAS_HEIGHT,
        rotation: 0,
        zIndex: 1,
        fill: '#3498DB',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Grid background
      createLockedElement<ShapeElement>({
        id: 'grid-bg',
        type: 'shape',
        shapeType: 'rectangle',
        x: 180,
        y: 0,
        width: CANVAS_WIDTH - 180,
        height: CANVAS_HEIGHT,
        rotation: 0,
        zIndex: 0,
        fill: '#F8F9FA',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Icon circle
      createLockedElement<ShapeElement>({
        id: 'icon-circle',
        type: 'shape',
        shapeType: 'circle',
        x: 50,
        y: 250,
        width: 80,
        height: 80,
        rotation: 0,
        zIndex: 2,
        fill: '#FFFFFF',
        stroke: 'transparent',
        strokeWidth: 0,
        locked: true,
        visible: true,
        opacity: 0.3,
      }),
      // Editable item text
      createEditableElement<TextElement>({
        id: 'item-text',
        type: 'text',
        content: 'Ground Beef',
        x: 690,
        y: 220,
        width: 800,
        height: 80,
        rotation: 0,
        zIndex: 10,
        fontSize: 64,
        fontFamily: 'Montserrat',
        fontWeight: 700,
        color: '#2C3E50',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 0,
        locked: false,
        visible: true,
        opacity: 1,
      }),
      // Editable date label
      createEditableElement<TextElement>({
        id: 'date-label',
        type: 'text',
        content: 'Frozen: 11/11/2025',
        x: 690,
        y: 360,
        width: 800,
        height: 50,
        rotation: 0,
        zIndex: 10,
        fontSize: 32,
        fontFamily: 'Inter',
        fontWeight: 500,
        color: '#7F8C8D',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 0,
        locked: false,
        visible: true,
        opacity: 1,
      }),
    ],
  },

  // 3. Meal Prep Freezer Label
  {
    metadata: {
      id: 'freezer-mealprep',
      name: 'Meal Prep',
      description: 'Organized label for meal prep containers',
      category: 'freezer',
      size: '4x2',
      tags: ['meal-prep', 'organized', 'detailed', 'functional'],
      difficulty: 'beginner',
      lockedElementIds: ['header-bg', 'info-box-1', 'info-box-2', 'divider-1', 'divider-2'],
      editableElementIds: ['meal-name', 'servings-text', 'date-frozen'],
    },
    backgroundColor: '#FFF5E6',
    elements: [
      // Header background
      createLockedElement<ShapeElement>({
        id: 'header-bg',
        type: 'shape',
        shapeType: 'rectangle',
        x: 0,
        y: 0,
        width: CANVAS_WIDTH,
        height: 180,
        rotation: 0,
        zIndex: 1,
        fill: '#FF9F43',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Info box 1
      createLockedElement<ShapeElement>({
        id: 'info-box-1',
        type: 'shape',
        shapeType: 'rectangle',
        x: 60,
        y: 240,
        width: 500,
        height: 300,
        rotation: 0,
        zIndex: 2,
        fill: '#FFFFFF',
        stroke: '#FF9F43',
        strokeWidth: 2,
        cornerRadius: 8,
        locked: true,
        visible: true,
        opacity: 0.9,
      }),
      // Info box 2
      createLockedElement<ShapeElement>({
        id: 'info-box-2',
        type: 'shape',
        shapeType: 'rectangle',
        x: 640,
        y: 240,
        width: 500,
        height: 300,
        rotation: 0,
        zIndex: 2,
        fill: '#FFFFFF',
        stroke: '#FF9F43',
        strokeWidth: 2,
        cornerRadius: 8,
        locked: true,
        visible: true,
        opacity: 0.9,
      }),
      // Divider 1
      createLockedElement<ShapeElement>({
        id: 'divider-1',
        type: 'shape',
        shapeType: 'rectangle',
        x: 80,
        y: 340,
        width: 460,
        height: 2,
        rotation: 0,
        zIndex: 3,
        fill: '#FFD8B2',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Divider 2
      createLockedElement<ShapeElement>({
        id: 'divider-2',
        type: 'shape',
        shapeType: 'rectangle',
        x: 660,
        y: 340,
        width: 460,
        height: 2,
        rotation: 0,
        zIndex: 3,
        fill: '#FFD8B2',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Editable meal name
      createEditableElement<TextElement>({
        id: 'meal-name',
        type: 'text',
        content: 'Lasagna',
        x: CANVAS_WIDTH / 2,
        y: 60,
        width: 1000,
        height: 100,
        rotation: 0,
        zIndex: 10,
        fontSize: 72,
        fontFamily: 'Poppins',
        fontWeight: 700,
        color: '#FFFFFF',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 1,
        locked: false,
        visible: true,
        opacity: 1,
      }),
      // Editable servings
      createEditableElement<TextElement>({
        id: 'servings-text',
        type: 'text',
        content: 'Servings: 6',
        x: 310,
        y: 380,
        width: 400,
        height: 60,
        rotation: 0,
        zIndex: 10,
        fontSize: 32,
        fontFamily: 'Inter',
        fontWeight: 600,
        color: '#E67E22',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 0,
        locked: false,
        visible: true,
        opacity: 1,
      }),
      // Editable date
      createEditableElement<TextElement>({
        id: 'date-frozen',
        type: 'text',
        content: '11/11/2025',
        x: 890,
        y: 380,
        width: 400,
        height: 60,
        rotation: 0,
        zIndex: 10,
        fontSize: 36,
        fontFamily: 'Inter',
        fontWeight: 700,
        color: '#E67E22',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 0,
        locked: false,
        visible: true,
        opacity: 1,
      }),
    ],
  },

  // 4. Simple Freezer Date Label
  {
    metadata: {
      id: 'freezer-simple',
      name: 'Simple Date Label',
      description: 'Minimalist freezer label with large text',
      category: 'freezer',
      size: '4x2',
      tags: ['simple', 'minimal', 'large-text', 'easy-read'],
      difficulty: 'beginner',
      lockedElementIds: ['bottom-bar'],
      editableElementIds: ['food-item', 'freeze-date'],
    },
    backgroundColor: '#F0F8FF',
    elements: [
      // Bottom accent bar
      createLockedElement<ShapeElement>({
        id: 'bottom-bar',
        type: 'shape',
        shapeType: 'rectangle',
        x: 0,
        y: 480,
        width: CANVAS_WIDTH,
        height: 120,
        rotation: 0,
        zIndex: 1,
        fill: '#4A90E2',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 0.2,
      }),
      // Editable food item
      createEditableElement<TextElement>({
        id: 'food-item',
        type: 'text',
        content: 'Soup - Chicken Noodle',
        x: CANVAS_WIDTH / 2,
        y: 160,
        width: 1000,
        height: 120,
        rotation: 0,
        zIndex: 10,
        fontSize: 68,
        fontFamily: 'Raleway',
        fontWeight: 700,
        color: '#2C3E50',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 0,
        locked: false,
        visible: true,
        opacity: 1,
      }),
      // Editable freeze date
      createEditableElement<TextElement>({
        id: 'freeze-date',
        type: 'text',
        content: 'Frozen: November 11, 2025',
        x: CANVAS_WIDTH / 2,
        y: 380,
        width: 900,
        height: 60,
        rotation: 0,
        zIndex: 10,
        fontSize: 38,
        fontFamily: 'Inter',
        fontWeight: 500,
        color: '#4A90E2',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 0,
        locked: false,
        visible: true,
        opacity: 1,
      }),
    ],
  },

  // 5. Color-Coded Freezer Label
  {
    metadata: {
      id: 'freezer-color',
      name: 'Color-Coded',
      description: 'Bright color-coded design for easy identification',
      category: 'freezer',
      size: '4x2',
      tags: ['colorful', 'organized', 'visual', 'bright'],
      difficulty: 'beginner',
      lockedElementIds: ['color-stripe-1', 'color-stripe-2', 'color-stripe-3', 'main-border'],
      editableElementIds: ['content-label', 'date-info', 'category-text'],
    },
    backgroundColor: '#FFFFFF',
    elements: [
      // Main border
      createLockedElement<ShapeElement>({
        id: 'main-border',
        type: 'shape',
        shapeType: 'rectangle',
        x: 15,
        y: 15,
        width: CANVAS_WIDTH - 30,
        height: CANVAS_HEIGHT - 30,
        rotation: 0,
        zIndex: 1,
        fill: 'transparent',
        stroke: '#34495E',
        strokeWidth: 4,
        cornerRadius: 10,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Color stripe 1
      createLockedElement<ShapeElement>({
        id: 'color-stripe-1',
        type: 'shape',
        shapeType: 'rectangle',
        x: 0,
        y: 0,
        width: CANVAS_WIDTH / 3,
        height: 40,
        rotation: 0,
        zIndex: 2,
        fill: '#E74C3C',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Color stripe 2
      createLockedElement<ShapeElement>({
        id: 'color-stripe-2',
        type: 'shape',
        shapeType: 'rectangle',
        x: CANVAS_WIDTH / 3,
        y: 0,
        width: CANVAS_WIDTH / 3,
        height: 40,
        rotation: 0,
        zIndex: 2,
        fill: '#F39C12',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Color stripe 3
      createLockedElement<ShapeElement>({
        id: 'color-stripe-3',
        type: 'shape',
        shapeType: 'rectangle',
        x: (CANVAS_WIDTH * 2) / 3,
        y: 0,
        width: CANVAS_WIDTH / 3,
        height: 40,
        rotation: 0,
        zIndex: 2,
        fill: '#27AE60',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Editable content label
      createEditableElement<TextElement>({
        id: 'content-label',
        type: 'text',
        content: 'Meatballs',
        x: CANVAS_WIDTH / 2,
        y: 200,
        width: 900,
        height: 100,
        rotation: 0,
        zIndex: 10,
        fontSize: 72,
        fontFamily: 'Poppins',
        fontWeight: 700,
        color: '#2C3E50',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 1,
        locked: false,
        visible: true,
        opacity: 1,
      }),
      // Editable date info
      createEditableElement<TextElement>({
        id: 'date-info',
        type: 'text',
        content: '11/11/2025',
        x: CANVAS_WIDTH / 2,
        y: 380,
        width: 600,
        height: 60,
        rotation: 0,
        zIndex: 10,
        fontSize: 42,
        fontFamily: 'Inter',
        fontWeight: 600,
        color: '#7F8C8D',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 0,
        locked: false,
        visible: true,
        opacity: 1,
      }),
      // Editable category
      createEditableElement<TextElement>({
        id: 'category-text',
        type: 'text',
        content: 'MEAT',
        x: CANVAS_WIDTH / 2,
        y: 90,
        width: 500,
        height: 50,
        rotation: 0,
        zIndex: 10,
        fontSize: 32,
        fontFamily: 'Bebas Neue',
        fontWeight: 700,
        color: '#95A5A6',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 3,
        locked: false,
        visible: true,
        opacity: 1,
      }),
    ],
  },
]
