import { Template, createLockedElement, createEditableElement } from './enhanced-types'
import { TextElement, ShapeElement } from '@/types/designer'

// Mason Jar templates use 2.25" × 1.25" size (675 x 375 pixels)
const CANVAS_WIDTH = 675
const CANVAS_HEIGHT = 375

export const masonJarTemplates: Template[] = [
  // 1. Classic Mason Jar Label
  {
    metadata: {
      id: 'mason-classic',
      name: 'Classic Mason Jar',
      description: 'Traditional mason jar label with ornate border',
      category: 'mason-jar',
      size: '2.25x1.25',
      tags: ['classic', 'vintage', 'border', 'traditional'],
      difficulty: 'beginner',
      lockedElementIds: ['border-outer', 'border-inner', 'corner-tl', 'corner-tr', 'corner-bl', 'corner-br'],
      editableElementIds: ['main-text', 'date-text'],
    },
    backgroundColor: '#FFF8E7',
    elements: [
      // Outer border
      createLockedElement<ShapeElement>({
        id: 'border-outer',
        type: 'shape',
        shapeType: 'rectangle',
        x: 20,
        y: 20,
        width: CANVAS_WIDTH - 40,
        height: CANVAS_HEIGHT - 40,
        rotation: 0,
        zIndex: 1,
        fill: 'transparent',
        stroke: '#8B4513',
        strokeWidth: 3,
        cornerRadius: 8,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Inner border
      createLockedElement<ShapeElement>({
        id: 'border-inner',
        type: 'shape',
        shapeType: 'rectangle',
        x: 30,
        y: 30,
        width: CANVAS_WIDTH - 60,
        height: CANVAS_HEIGHT - 60,
        rotation: 0,
        zIndex: 2,
        fill: 'transparent',
        stroke: '#D2691E',
        strokeWidth: 1,
        cornerRadius: 6,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Decorative corners
      createLockedElement<ShapeElement>({
        id: 'corner-tl',
        type: 'shape',
        shapeType: 'circle',
        x: 15,
        y: 15,
        width: 10,
        height: 10,
        rotation: 0,
        zIndex: 3,
        fill: '#8B4513',
        stroke: 'transparent',
        strokeWidth: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      createLockedElement<ShapeElement>({
        id: 'corner-tr',
        type: 'shape',
        shapeType: 'circle',
        x: CANVAS_WIDTH - 25,
        y: 15,
        width: 10,
        height: 10,
        rotation: 0,
        zIndex: 3,
        fill: '#8B4513',
        stroke: 'transparent',
        strokeWidth: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      createLockedElement<ShapeElement>({
        id: 'corner-bl',
        type: 'shape',
        shapeType: 'circle',
        x: 15,
        y: CANVAS_HEIGHT - 25,
        width: 10,
        height: 10,
        rotation: 0,
        zIndex: 3,
        fill: '#8B4513',
        stroke: 'transparent',
        strokeWidth: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      createLockedElement<ShapeElement>({
        id: 'corner-br',
        type: 'shape',
        shapeType: 'circle',
        x: CANVAS_WIDTH - 25,
        y: CANVAS_HEIGHT - 25,
        width: 10,
        height: 10,
        rotation: 0,
        zIndex: 3,
        fill: '#8B4513',
        stroke: 'transparent',
        strokeWidth: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Editable main text
      createEditableElement<TextElement>({
        id: 'main-text',
        type: 'text',
        content: 'Strawberry Jam',
        x: CANVAS_WIDTH / 2,
        y: 140,
        width: 500,
        height: 60,
        rotation: 0,
        zIndex: 10,
        fontSize: 48,
        fontFamily: 'Playfair Display',
        fontWeight: 700,
        color: '#8B4513',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 0,
        locked: false,
        visible: true,
        opacity: 1,
      }),
      // Editable date text
      createEditableElement<TextElement>({
        id: 'date-text',
        type: 'text',
        content: 'Made: November 2025',
        x: CANVAS_WIDTH / 2,
        y: 240,
        width: 400,
        height: 30,
        rotation: 0,
        zIndex: 10,
        fontSize: 20,
        fontFamily: 'Lora',
        fontWeight: 400,
        color: '#654321',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 0,
        locked: false,
        visible: true,
        opacity: 1,
      }),
    ],
  },

  // 2. Rustic Farmhouse Label
  {
    metadata: {
      id: 'mason-farmhouse',
      name: 'Rustic Farmhouse',
      description: 'Warm farmhouse style with wood-grain background',
      category: 'mason-jar',
      size: '2.25x1.25',
      tags: ['rustic', 'farmhouse', 'modern', 'clean'],
      difficulty: 'beginner',
      lockedElementIds: ['bg-rect', 'accent-line'],
      editableElementIds: ['title-text', 'subtitle-text'],
    },
    backgroundColor: '#F5E6D3',
    elements: [
      // Background accent rectangle
      createLockedElement<ShapeElement>({
        id: 'bg-rect',
        type: 'shape',
        shapeType: 'rectangle',
        x: 0,
        y: 100,
        width: CANVAS_WIDTH,
        height: 175,
        rotation: 0,
        zIndex: 1,
        fill: '#DEB887',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 0.3,
      }),
      // Accent line
      createLockedElement<ShapeElement>({
        id: 'accent-line',
        type: 'shape',
        shapeType: 'rectangle',
        x: 50,
        y: 160,
        width: CANVAS_WIDTH - 100,
        height: 2,
        rotation: 0,
        zIndex: 2,
        fill: '#8B4513',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Editable title
      createEditableElement<TextElement>({
        id: 'title-text',
        type: 'text',
        content: 'HOMEMADE',
        x: CANVAS_WIDTH / 2,
        y: 100,
        width: 550,
        height: 50,
        rotation: 0,
        zIndex: 10,
        fontSize: 36,
        fontFamily: 'Bebas Neue',
        fontWeight: 700,
        color: '#2C1810',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 3,
        locked: false,
        visible: true,
        opacity: 1,
      }),
      // Editable subtitle
      createEditableElement<TextElement>({
        id: 'subtitle-text',
        type: 'text',
        content: 'Peach Preserves',
        x: CANVAS_WIDTH / 2,
        y: 185,
        width: 550,
        height: 70,
        rotation: 0,
        zIndex: 10,
        fontSize: 44,
        fontFamily: 'Crimson Text',
        fontWeight: 600,
        color: '#8B4513',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 0,
        fontStyle: 'italic',
        locked: false,
        visible: true,
        opacity: 1,
      }),
    ],
  },

  // 3. Modern Minimalist Label
  {
    metadata: {
      id: 'mason-minimalist',
      name: 'Modern Minimalist',
      description: 'Clean and simple modern design',
      category: 'mason-jar',
      size: '2.25x1.25',
      tags: ['modern', 'minimalist', 'clean', 'simple'],
      difficulty: 'beginner',
      lockedElementIds: ['top-line', 'bottom-line', 'left-accent', 'right-accent'],
      editableElementIds: ['content-text', 'label-text'],
    },
    backgroundColor: '#FFFFFF',
    elements: [
      // Top line
      createLockedElement<ShapeElement>({
        id: 'top-line',
        type: 'shape',
        shapeType: 'rectangle',
        x: 100,
        y: 80,
        width: CANVAS_WIDTH - 200,
        height: 1,
        rotation: 0,
        zIndex: 1,
        fill: '#000000',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Bottom line
      createLockedElement<ShapeElement>({
        id: 'bottom-line',
        type: 'shape',
        shapeType: 'rectangle',
        x: 100,
        y: 294,
        width: CANVAS_WIDTH - 200,
        height: 1,
        rotation: 0,
        zIndex: 1,
        fill: '#000000',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Left accent
      createLockedElement<ShapeElement>({
        id: 'left-accent',
        type: 'shape',
        shapeType: 'rectangle',
        x: 80,
        y: 170,
        width: 3,
        height: 35,
        rotation: 0,
        zIndex: 2,
        fill: '#000000',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Right accent
      createLockedElement<ShapeElement>({
        id: 'right-accent',
        type: 'shape',
        shapeType: 'rectangle',
        x: CANVAS_WIDTH - 83,
        y: 170,
        width: 3,
        height: 35,
        rotation: 0,
        zIndex: 2,
        fill: '#000000',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Editable content name
      createEditableElement<TextElement>({
        id: 'content-text',
        type: 'text',
        content: 'Blueberry Jam',
        x: CANVAS_WIDTH / 2,
        y: 150,
        width: 500,
        height: 60,
        rotation: 0,
        zIndex: 10,
        fontSize: 42,
        fontFamily: 'Montserrat',
        fontWeight: 600,
        color: '#000000',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 1,
        locked: false,
        visible: true,
        opacity: 1,
      }),
      // Editable label
      createEditableElement<TextElement>({
        id: 'label-text',
        type: 'text',
        content: '2025',
        x: CANVAS_WIDTH / 2,
        y: 230,
        width: 300,
        height: 30,
        rotation: 0,
        zIndex: 10,
        fontSize: 18,
        fontFamily: 'Inter',
        fontWeight: 400,
        color: '#666666',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 2,
        locked: false,
        visible: true,
        opacity: 1,
      }),
    ],
  },

  // 4. Vintage Apothecary Label
  {
    metadata: {
      id: 'mason-apothecary',
      name: 'Vintage Apothecary',
      description: 'Old-fashioned apothecary style label',
      category: 'mason-jar',
      size: '2.25x1.25',
      tags: ['vintage', 'apothecary', 'ornate', 'classic'],
      difficulty: 'intermediate',
      lockedElementIds: ['bg-banner', 'top-flourish', 'bottom-flourish', 'frame-rect'],
      editableElementIds: ['product-text', 'detail-text', 'year-text'],
    },
    backgroundColor: '#E8DCC4',
    elements: [
      // Background banner
      createLockedElement<ShapeElement>({
        id: 'bg-banner',
        type: 'shape',
        shapeType: 'rectangle',
        x: 40,
        y: 120,
        width: CANVAS_WIDTH - 80,
        height: 135,
        rotation: 0,
        zIndex: 1,
        fill: '#3A2F28',
        stroke: '#D4AF37',
        strokeWidth: 2,
        cornerRadius: 4,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Frame rectangle
      createLockedElement<ShapeElement>({
        id: 'frame-rect',
        type: 'shape',
        shapeType: 'rectangle',
        x: 15,
        y: 15,
        width: CANVAS_WIDTH - 30,
        height: CANVAS_HEIGHT - 30,
        rotation: 0,
        zIndex: 0,
        fill: 'transparent',
        stroke: '#8B7355',
        strokeWidth: 2,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Top flourish line
      createLockedElement<ShapeElement>({
        id: 'top-flourish',
        type: 'shape',
        shapeType: 'rectangle',
        x: 150,
        y: 90,
        width: CANVAS_WIDTH - 300,
        height: 1,
        rotation: 0,
        zIndex: 2,
        fill: '#8B7355',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Bottom flourish line
      createLockedElement<ShapeElement>({
        id: 'bottom-flourish',
        type: 'shape',
        shapeType: 'rectangle',
        x: 150,
        y: 285,
        width: CANVAS_WIDTH - 300,
        height: 1,
        rotation: 0,
        zIndex: 2,
        fill: '#8B7355',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Editable product text
      createEditableElement<TextElement>({
        id: 'product-text',
        type: 'text',
        content: 'CHERRY',
        x: CANVAS_WIDTH / 2,
        y: 140,
        width: 500,
        height: 40,
        rotation: 0,
        zIndex: 10,
        fontSize: 36,
        fontFamily: 'Bebas Neue',
        fontWeight: 700,
        color: '#D4AF37',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 4,
        locked: false,
        visible: true,
        opacity: 1,
      }),
      // Editable detail text
      createEditableElement<TextElement>({
        id: 'detail-text',
        type: 'text',
        content: 'Preserves',
        x: CANVAS_WIDTH / 2,
        y: 190,
        width: 450,
        height: 50,
        rotation: 0,
        zIndex: 10,
        fontSize: 32,
        fontFamily: 'Playfair Display',
        fontWeight: 400,
        color: '#F5E6D3',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 1,
        fontStyle: 'italic',
        locked: false,
        visible: true,
        opacity: 1,
      }),
      // Editable year
      createEditableElement<TextElement>({
        id: 'year-text',
        type: 'text',
        content: 'Est. 2025',
        x: CANVAS_WIDTH / 2,
        y: 50,
        width: 300,
        height: 25,
        rotation: 0,
        zIndex: 10,
        fontSize: 16,
        fontFamily: 'Courier New',
        fontWeight: 400,
        color: '#6B5644',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 1,
        locked: false,
        visible: true,
        opacity: 1,
      }),
    ],
  },

  // 5. Garden Fresh Label
  {
    metadata: {
      id: 'mason-garden',
      name: 'Garden Fresh',
      description: 'Fresh garden-inspired design with leaf accents',
      category: 'mason-jar',
      size: '2.25x1.25',
      tags: ['fresh', 'garden', 'organic', 'natural'],
      difficulty: 'beginner',
      lockedElementIds: ['leaf-left', 'leaf-right', 'divider-top', 'divider-bottom'],
      editableElementIds: ['main-label-text', 'from-text'],
    },
    backgroundColor: '#F0F8F0',
    elements: [
      // Left leaf accent
      createLockedElement<ShapeElement>({
        id: 'leaf-left',
        type: 'shape',
        shapeType: 'circle',
        x: 60,
        y: 165,
        width: 40,
        height: 45,
        rotation: -30,
        zIndex: 1,
        fill: '#5C8A4D',
        stroke: 'transparent',
        strokeWidth: 0,
        locked: true,
        visible: true,
        opacity: 0.3,
      }),
      // Right leaf accent
      createLockedElement<ShapeElement>({
        id: 'leaf-right',
        type: 'shape',
        shapeType: 'circle',
        x: CANVAS_WIDTH - 100,
        y: 165,
        width: 40,
        height: 45,
        rotation: 30,
        zIndex: 1,
        fill: '#5C8A4D',
        stroke: 'transparent',
        strokeWidth: 0,
        locked: true,
        visible: true,
        opacity: 0.3,
      }),
      // Top divider
      createLockedElement<ShapeElement>({
        id: 'divider-top',
        type: 'shape',
        shapeType: 'rectangle',
        x: 180,
        y: 130,
        width: CANVAS_WIDTH - 360,
        height: 2,
        rotation: 0,
        zIndex: 2,
        fill: '#5C8A4D',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 0.5,
      }),
      // Bottom divider
      createLockedElement<ShapeElement>({
        id: 'divider-bottom',
        type: 'shape',
        shapeType: 'rectangle',
        x: 180,
        y: 243,
        width: CANVAS_WIDTH - 360,
        height: 2,
        rotation: 0,
        zIndex: 2,
        fill: '#5C8A4D',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 0.5,
      }),
      // Editable main label
      createEditableElement<TextElement>({
        id: 'main-label-text',
        type: 'text',
        content: 'Tomato Sauce',
        x: CANVAS_WIDTH / 2,
        y: 155,
        width: 500,
        height: 70,
        rotation: 0,
        zIndex: 10,
        fontSize: 46,
        fontFamily: 'Satisfy',
        fontWeight: 400,
        color: '#2D5016',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 0,
        locked: false,
        visible: true,
        opacity: 1,
      }),
      // Editable from text
      createEditableElement<TextElement>({
        id: 'from-text',
        type: 'text',
        content: 'from our garden',
        x: CANVAS_WIDTH / 2,
        y: 80,
        width: 400,
        height: 30,
        rotation: 0,
        zIndex: 10,
        fontSize: 20,
        fontFamily: 'Dancing Script',
        fontWeight: 400,
        color: '#5C8A4D',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 0,
        locked: false,
        visible: true,
        opacity: 1,
      }),
    ],
  },
]
