import { Template, createLockedElement, createEditableElement } from './enhanced-types'
import { TextElement, ShapeElement } from '@/types/designer'

// Pantry templates use 3" × 2" size (900 x 600 pixels)
const CANVAS_WIDTH = 900
const CANVAS_HEIGHT = 600

export const pantryTemplates: Template[] = [
  // 1. Classic Pantry Label
  {
    metadata: {
      id: 'pantry-classic',
      name: 'Classic Pantry',
      description: 'Traditional pantry label with border',
      category: 'pantry',
      size: '3x2',
      tags: ['classic', 'traditional', 'simple', 'organized'],
      difficulty: 'beginner',
      lockedElementIds: ['main-border', 'inner-border', 'corner-accent-1', 'corner-accent-2'],
      editableElementIds: ['item-name', 'expiry-text'],
    },
    backgroundColor: '#FFFEF7',
    elements: [
      // Main border
      createLockedElement<ShapeElement>({
        id: 'main-border',
        type: 'shape',
        shapeType: 'rectangle',
        x: 25,
        y: 25,
        width: CANVAS_WIDTH - 50,
        height: CANVAS_HEIGHT - 50,
        rotation: 0,
        zIndex: 1,
        fill: 'transparent',
        stroke: '#8B6F47',
        strokeWidth: 3,
        cornerRadius: 8,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Inner border
      createLockedElement<ShapeElement>({
        id: 'inner-border',
        type: 'shape',
        shapeType: 'rectangle',
        x: 35,
        y: 35,
        width: CANVAS_WIDTH - 70,
        height: CANVAS_HEIGHT - 70,
        rotation: 0,
        zIndex: 2,
        fill: 'transparent',
        stroke: '#C19A6B',
        strokeWidth: 1,
        cornerRadius: 6,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Corner accent 1
      createLockedElement<ShapeElement>({
        id: 'corner-accent-1',
        type: 'shape',
        shapeType: 'rectangle',
        x: 60,
        y: 230,
        width: 120,
        height: 2,
        rotation: 0,
        zIndex: 3,
        fill: '#8B6F47',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Corner accent 2
      createLockedElement<ShapeElement>({
        id: 'corner-accent-2',
        type: 'shape',
        shapeType: 'rectangle',
        x: CANVAS_WIDTH - 180,
        y: 230,
        width: 120,
        height: 2,
        rotation: 0,
        zIndex: 3,
        fill: '#8B6F47',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Editable item name
      createEditableElement<TextElement>({
        id: 'item-name',
        type: 'text',
        content: 'All-Purpose Flour',
        x: CANVAS_WIDTH / 2,
        y: 220,
        width: 750,
        height: 100,
        rotation: 0,
        zIndex: 10,
        fontSize: 62,
        fontFamily: 'Playfair Display',
        fontWeight: 700,
        color: '#5D4E37',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 0,
        locked: false,
        visible: true,
        opacity: 1,
      }),
      // Editable expiry
      createEditableElement<TextElement>({
        id: 'expiry-text',
        type: 'text',
        content: 'Best by: Dec 2026',
        x: CANVAS_WIDTH / 2,
        y: 400,
        width: 600,
        height: 50,
        rotation: 0,
        zIndex: 10,
        fontSize: 28,
        fontFamily: 'Lora',
        fontWeight: 400,
        color: '#8B6F47',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 0,
        locked: false,
        visible: true,
        opacity: 1,
      }),
    ],
  },

  // 2. Modern Pantry Organization
  {
    metadata: {
      id: 'pantry-modern',
      name: 'Modern Organization',
      description: 'Clean modern design with category indicator',
      category: 'pantry',
      size: '3x2',
      tags: ['modern', 'organized', 'clean', 'category'],
      difficulty: 'beginner',
      lockedElementIds: ['category-bar', 'divider-line', 'dot-accent'],
      editableElementIds: ['product-name', 'category-label', 'quantity-text'],
    },
    backgroundColor: '#FFFFFF',
    elements: [
      // Category color bar
      createLockedElement<ShapeElement>({
        id: 'category-bar',
        type: 'shape',
        shapeType: 'rectangle',
        x: 0,
        y: 0,
        width: 140,
        height: CANVAS_HEIGHT,
        rotation: 0,
        zIndex: 1,
        fill: '#27AE60',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Dot accent
      createLockedElement<ShapeElement>({
        id: 'dot-accent',
        type: 'shape',
        shapeType: 'circle',
        x: 50,
        y: 270,
        width: 40,
        height: 40,
        rotation: 0,
        zIndex: 2,
        fill: '#FFFFFF',
        stroke: 'transparent',
        strokeWidth: 0,
        locked: true,
        visible: true,
        opacity: 0.4,
      }),
      // Divider line
      createLockedElement<ShapeElement>({
        id: 'divider-line',
        type: 'shape',
        shapeType: 'rectangle',
        x: 200,
        y: 360,
        width: 620,
        height: 2,
        rotation: 0,
        zIndex: 3,
        fill: '#ECF0F1',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Editable product name
      createEditableElement<TextElement>({
        id: 'product-name',
        type: 'text',
        content: 'Brown Rice',
        x: 520,
        y: 220,
        width: 650,
        height: 100,
        rotation: 0,
        zIndex: 10,
        fontSize: 64,
        fontFamily: 'Montserrat',
        fontWeight: 700,
        color: '#2C3E50',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 0,
        locked: false,
        visible: true,
        opacity: 1,
      }),
      // Editable category
      createEditableElement<TextElement>({
        id: 'category-label',
        type: 'text',
        content: 'GRAINS',
        x: 520,
        y: 110,
        width: 650,
        height: 50,
        rotation: 0,
        zIndex: 10,
        fontSize: 32,
        fontFamily: 'Bebas Neue',
        fontWeight: 700,
        color: '#95A5A6',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 3,
        locked: false,
        visible: true,
        opacity: 1,
      }),
      // Editable quantity
      createEditableElement<TextElement>({
        id: 'quantity-text',
        type: 'text',
        content: 'Qty: 2 lbs',
        x: 520,
        y: 420,
        width: 500,
        height: 50,
        rotation: 0,
        zIndex: 10,
        fontSize: 32,
        fontFamily: 'Inter',
        fontWeight: 500,
        color: '#7F8C8D',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 0,
        locked: false,
        visible: true,
        opacity: 1,
      }),
    ],
  },

  // 3. Farmhouse Pantry Label
  {
    metadata: {
      id: 'pantry-farmhouse',
      name: 'Farmhouse Style',
      description: 'Rustic farmhouse design with warm tones',
      category: 'pantry',
      size: '3x2',
      tags: ['farmhouse', 'rustic', 'warm', 'cozy'],
      difficulty: 'beginner',
      lockedElementIds: ['bg-panel', 'top-flourish', 'bottom-flourish', 'center-accent'],
      editableElementIds: ['pantry-item', 'opened-date'],
    },
    backgroundColor: '#F5E6D3',
    elements: [
      // Background panel
      createLockedElement<ShapeElement>({
        id: 'bg-panel',
        type: 'shape',
        shapeType: 'rectangle',
        x: 80,
        y: 150,
        width: CANVAS_WIDTH - 160,
        height: 300,
        rotation: 0,
        zIndex: 1,
        fill: '#DEB887',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 10,
        locked: true,
        visible: true,
        opacity: 0.3,
      }),
      // Top flourish
      createLockedElement<ShapeElement>({
        id: 'top-flourish',
        type: 'shape',
        shapeType: 'rectangle',
        x: 250,
        y: 120,
        width: 400,
        height: 3,
        rotation: 0,
        zIndex: 2,
        fill: '#8B4513',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 0.6,
      }),
      // Bottom flourish
      createLockedElement<ShapeElement>({
        id: 'bottom-flourish',
        type: 'shape',
        shapeType: 'rectangle',
        x: 250,
        y: 477,
        width: 400,
        height: 3,
        rotation: 0,
        zIndex: 2,
        fill: '#8B4513',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 0.6,
      }),
      // Center accent
      createLockedElement<ShapeElement>({
        id: 'center-accent',
        type: 'shape',
        shapeType: 'circle',
        x: CANVAS_WIDTH / 2 - 50,
        y: 250,
        width: 100,
        height: 100,
        rotation: 0,
        zIndex: 2,
        fill: 'transparent',
        stroke: '#8B4513',
        strokeWidth: 2,
        locked: true,
        visible: true,
        opacity: 0.2,
      }),
      // Editable pantry item
      createEditableElement<TextElement>({
        id: 'pantry-item',
        type: 'text',
        content: 'Oats',
        x: CANVAS_WIDTH / 2,
        y: 250,
        width: 700,
        height: 100,
        rotation: 0,
        zIndex: 10,
        fontSize: 72,
        fontFamily: 'Crimson Text',
        fontWeight: 600,
        color: '#5D4E37',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 1,
        fontStyle: 'italic',
        locked: false,
        visible: true,
        opacity: 1,
      }),
      // Editable opened date
      createEditableElement<TextElement>({
        id: 'opened-date',
        type: 'text',
        content: 'Opened: Nov 2025',
        x: CANVAS_WIDTH / 2,
        y: 400,
        width: 600,
        height: 50,
        rotation: 0,
        zIndex: 10,
        fontSize: 28,
        fontFamily: 'Lora',
        fontWeight: 400,
        color: '#8B6F47',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 0,
        locked: false,
        visible: true,
        opacity: 1,
      }),
    ],
  },

  // 4. Minimal Pantry Label
  {
    metadata: {
      id: 'pantry-minimal',
      name: 'Minimal Clean',
      description: 'Ultra-clean minimalist design',
      category: 'pantry',
      size: '3x2',
      tags: ['minimal', 'clean', 'simple', 'modern'],
      difficulty: 'beginner',
      lockedElementIds: ['top-line', 'bottom-line', 'left-mark', 'right-mark'],
      editableElementIds: ['content-name'],
    },
    backgroundColor: '#FAFAFA',
    elements: [
      // Top line
      createLockedElement<ShapeElement>({
        id: 'top-line',
        type: 'shape',
        shapeType: 'rectangle',
        x: 150,
        y: 150,
        width: CANVAS_WIDTH - 300,
        height: 1,
        rotation: 0,
        zIndex: 1,
        fill: '#000000',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Bottom line
      createLockedElement<ShapeElement>({
        id: 'bottom-line',
        type: 'shape',
        shapeType: 'rectangle',
        x: 150,
        y: 449,
        width: CANVAS_WIDTH - 300,
        height: 1,
        rotation: 0,
        zIndex: 1,
        fill: '#000000',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Left mark
      createLockedElement<ShapeElement>({
        id: 'left-mark',
        type: 'shape',
        shapeType: 'rectangle',
        x: 130,
        y: 285,
        width: 3,
        height: 30,
        rotation: 0,
        zIndex: 2,
        fill: '#000000',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Right mark
      createLockedElement<ShapeElement>({
        id: 'right-mark',
        type: 'shape',
        shapeType: 'rectangle',
        x: CANVAS_WIDTH - 133,
        y: 285,
        width: 3,
        height: 30,
        rotation: 0,
        zIndex: 2,
        fill: '#000000',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Editable content name
      createEditableElement<TextElement>({
        id: 'content-name',
        type: 'text',
        content: 'Quinoa',
        x: CANVAS_WIDTH / 2,
        y: 260,
        width: 700,
        height: 80,
        rotation: 0,
        zIndex: 10,
        fontSize: 64,
        fontFamily: 'Inter',
        fontWeight: 300,
        color: '#000000',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 2,
        locked: false,
        visible: true,
        opacity: 1,
      }),
    ],
  },

  // 5. Vintage Pantry Label
  {
    metadata: {
      id: 'pantry-vintage',
      name: 'Vintage Pantry',
      description: 'Old-fashioned vintage style pantry label',
      category: 'pantry',
      size: '3x2',
      tags: ['vintage', 'retro', 'classic', 'ornate'],
      difficulty: 'intermediate',
      lockedElementIds: ['outer-frame', 'inner-frame', 'banner-bg', 'top-ornament', 'bottom-ornament'],
      editableElementIds: ['product-text', 'subtitle-text'],
    },
    backgroundColor: '#E8DCC4',
    elements: [
      // Outer frame
      createLockedElement<ShapeElement>({
        id: 'outer-frame',
        type: 'shape',
        shapeType: 'rectangle',
        x: 30,
        y: 30,
        width: CANVAS_WIDTH - 60,
        height: CANVAS_HEIGHT - 60,
        rotation: 0,
        zIndex: 1,
        fill: 'transparent',
        stroke: '#6B5644',
        strokeWidth: 3,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Inner frame
      createLockedElement<ShapeElement>({
        id: 'inner-frame',
        type: 'shape',
        shapeType: 'rectangle',
        x: 45,
        y: 45,
        width: CANVAS_WIDTH - 90,
        height: CANVAS_HEIGHT - 90,
        rotation: 0,
        zIndex: 2,
        fill: 'transparent',
        stroke: '#A0826D',
        strokeWidth: 1,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Banner background
      createLockedElement<ShapeElement>({
        id: 'banner-bg',
        type: 'shape',
        shapeType: 'rectangle',
        x: 90,
        y: 220,
        width: CANVAS_WIDTH - 180,
        height: 160,
        rotation: 0,
        zIndex: 3,
        fill: '#3A2F28',
        stroke: '#D4AF37',
        strokeWidth: 2,
        cornerRadius: 5,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Top ornament
      createLockedElement<ShapeElement>({
        id: 'top-ornament',
        type: 'shape',
        shapeType: 'circle',
        x: CANVAS_WIDTH / 2 - 15,
        y: 80,
        width: 30,
        height: 30,
        rotation: 0,
        zIndex: 4,
        fill: '#6B5644',
        stroke: 'transparent',
        strokeWidth: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Bottom ornament
      createLockedElement<ShapeElement>({
        id: 'bottom-ornament',
        type: 'shape',
        shapeType: 'circle',
        x: CANVAS_WIDTH / 2 - 15,
        y: 490,
        width: 30,
        height: 30,
        rotation: 0,
        zIndex: 4,
        fill: '#6B5644',
        stroke: 'transparent',
        strokeWidth: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Editable product
      createEditableElement<TextElement>({
        id: 'product-text',
        type: 'text',
        content: 'PASTA',
        x: CANVAS_WIDTH / 2,
        y: 245,
        width: 600,
        height: 60,
        rotation: 0,
        zIndex: 10,
        fontSize: 52,
        fontFamily: 'Bebas Neue',
        fontWeight: 700,
        color: '#D4AF37',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 5,
        locked: false,
        visible: true,
        opacity: 1,
      }),
      // Editable subtitle
      createEditableElement<TextElement>({
        id: 'subtitle-text',
        type: 'text',
        content: 'Penne',
        x: CANVAS_WIDTH / 2,
        y: 315,
        width: 550,
        height: 60,
        rotation: 0,
        zIndex: 10,
        fontSize: 42,
        fontFamily: 'Playfair Display',
        fontWeight: 400,
        color: '#F5E6D3',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 1,
        fontStyle: 'italic',
        locked: false,
        visible: true,
        opacity: 1,
      }),
    ],
  },
]
