import { Template, createLockedElement, createEditableElement } from './enhanced-types'
import { TextElement, ShapeElement } from '@/types/designer'

// School templates use 3" × 2" size (900 x 600 pixels)
const CANVAS_WIDTH = 900
const CANVAS_HEIGHT = 600

export const schoolTemplates: Template[] = [
  // 1. Classic School Name Label
  {
    metadata: {
      id: 'school-classic',
      name: 'Classic Name Label',
      description: 'Traditional school name label with bright colors',
      category: 'school',
      size: '3x2',
      tags: ['name', 'classic', 'colorful', 'kid-friendly'],
      difficulty: 'beginner',
      lockedElementIds: ['border-rect', 'stripe-top', 'stripe-bottom', 'star-1', 'star-2'],
      editableElementIds: ['student-name', 'grade-text'],
    },
    backgroundColor: '#FFF9E6',
    elements: [
      // Border rectangle
      createLockedElement<ShapeElement>({
        id: 'border-rect',
        type: 'shape',
        shapeType: 'rectangle',
        x: 20,
        y: 20,
        width: CANVAS_WIDTH - 40,
        height: CANVAS_HEIGHT - 40,
        rotation: 0,
        zIndex: 1,
        fill: 'transparent',
        stroke: '#FF6B6B',
        strokeWidth: 4,
        cornerRadius: 12,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Top stripe
      createLockedElement<ShapeElement>({
        id: 'stripe-top',
        type: 'shape',
        shapeType: 'rectangle',
        x: 0,
        y: 0,
        width: CANVAS_WIDTH,
        height: 100,
        rotation: 0,
        zIndex: 2,
        fill: '#4ECDC4',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 0.2,
      }),
      // Bottom stripe
      createLockedElement<ShapeElement>({
        id: 'stripe-bottom',
        type: 'shape',
        shapeType: 'rectangle',
        x: 0,
        y: 500,
        width: CANVAS_WIDTH,
        height: 100,
        rotation: 0,
        zIndex: 2,
        fill: '#FFE66D',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 0.2,
      }),
      // Star decoration 1
      createLockedElement<ShapeElement>({
        id: 'star-1',
        type: 'shape',
        shapeType: 'circle',
        x: 70,
        y: 270,
        width: 35,
        height: 35,
        rotation: 0,
        zIndex: 3,
        fill: '#FFE66D',
        stroke: 'transparent',
        strokeWidth: 0,
        locked: true,
        visible: true,
        opacity: 0.4,
      }),
      // Star decoration 2
      createLockedElement<ShapeElement>({
        id: 'star-2',
        type: 'shape',
        shapeType: 'circle',
        x: CANVAS_WIDTH - 105,
        y: 270,
        width: 35,
        height: 35,
        rotation: 0,
        zIndex: 3,
        fill: '#FF6B6B',
        stroke: 'transparent',
        strokeWidth: 0,
        locked: true,
        visible: true,
        opacity: 0.4,
      }),
      // Editable student name
      createEditableElement<TextElement>({
        id: 'student-name',
        type: 'text',
        content: 'Emma Johnson',
        x: CANVAS_WIDTH / 2,
        y: 235,
        width: 750,
        height: 90,
        rotation: 0,
        zIndex: 10,
        fontSize: 68,
        fontFamily: 'Fredoka',
        fontWeight: 700,
        color: '#2C3E50',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 0,
        locked: false,
        visible: true,
        opacity: 1,
      }),
      // Editable grade
      createEditableElement<TextElement>({
        id: 'grade-text',
        type: 'text',
        content: 'Grade 3',
        x: CANVAS_WIDTH / 2,
        y: 390,
        width: 500,
        height: 50,
        rotation: 0,
        zIndex: 10,
        fontSize: 36,
        fontFamily: 'Poppins',
        fontWeight: 600,
        color: '#7F8C8D',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 1,
        locked: false,
        visible: true,
        opacity: 1,
      }),
    ],
  },

  // 2. Notebook Label
  {
    metadata: {
      id: 'school-notebook',
      name: 'Notebook Label',
      description: 'Clean notebook-style label with lines',
      category: 'school',
      size: '3x2',
      tags: ['notebook', 'organized', 'subject', 'clean'],
      difficulty: 'beginner',
      lockedElementIds: ['margin-line', 'ruled-line-1', 'ruled-line-2', 'ruled-line-3', 'header-bg'],
      editableElementIds: ['subject-text', 'name-field', 'period-text'],
    },
    backgroundColor: '#FFFFFF',
    elements: [
      // Header background
      createLockedElement<ShapeElement>({
        id: 'header-bg',
        type: 'shape',
        shapeType: 'rectangle',
        x: 0,
        y: 0,
        width: CANVAS_WIDTH,
        height: 140,
        rotation: 0,
        zIndex: 1,
        fill: '#3498DB',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Margin line (like notebook paper)
      createLockedElement<ShapeElement>({
        id: 'margin-line',
        type: 'shape',
        shapeType: 'rectangle',
        x: 80,
        y: 140,
        width: 2,
        height: CANVAS_HEIGHT - 140,
        rotation: 0,
        zIndex: 2,
        fill: '#E74C3C',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 0.4,
      }),
      // Ruled line 1
      createLockedElement<ShapeElement>({
        id: 'ruled-line-1',
        type: 'shape',
        shapeType: 'rectangle',
        x: 100,
        y: 290,
        width: CANVAS_WIDTH - 120,
        height: 1,
        rotation: 0,
        zIndex: 3,
        fill: '#BDC3C7',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Ruled line 2
      createLockedElement<ShapeElement>({
        id: 'ruled-line-2',
        type: 'shape',
        shapeType: 'rectangle',
        x: 100,
        y: 380,
        width: CANVAS_WIDTH - 120,
        height: 1,
        rotation: 0,
        zIndex: 3,
        fill: '#BDC3C7',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Ruled line 3
      createLockedElement<ShapeElement>({
        id: 'ruled-line-3',
        type: 'shape',
        shapeType: 'rectangle',
        x: 100,
        y: 470,
        width: CANVAS_WIDTH - 120,
        height: 1,
        rotation: 0,
        zIndex: 3,
        fill: '#BDC3C7',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Editable subject
      createEditableElement<TextElement>({
        id: 'subject-text',
        type: 'text',
        content: 'MATH',
        x: CANVAS_WIDTH / 2,
        y: 50,
        width: 700,
        height: 80,
        rotation: 0,
        zIndex: 10,
        fontSize: 64,
        fontFamily: 'Bebas Neue',
        fontWeight: 700,
        color: '#FFFFFF',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 5,
        locked: false,
        visible: true,
        opacity: 1,
      }),
      // Editable name
      createEditableElement<TextElement>({
        id: 'name-field',
        type: 'text',
        content: 'Sophia Martinez',
        x: CANVAS_WIDTH / 2,
        y: 215,
        width: 700,
        height: 60,
        rotation: 0,
        zIndex: 10,
        fontSize: 44,
        fontFamily: 'Poppins',
        fontWeight: 600,
        color: '#34495E',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 0,
        locked: false,
        visible: true,
        opacity: 1,
      }),
      // Editable period
      createEditableElement<TextElement>({
        id: 'period-text',
        type: 'text',
        content: 'Period 2',
        x: CANVAS_WIDTH / 2,
        y: 510,
        width: 500,
        height: 40,
        rotation: 0,
        zIndex: 10,
        fontSize: 28,
        fontFamily: 'Inter',
        fontWeight: 500,
        color: '#7F8C8D',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 0,
        locked: false,
        visible: true,
        opacity: 1,
      }),
    ],
  },

  // 3. Colorful Supply Label
  {
    metadata: {
      id: 'school-supplies',
      name: 'Supply Label',
      description: 'Bright and colorful label for school supplies',
      category: 'school',
      size: '3x2',
      tags: ['supplies', 'colorful', 'fun', 'bright'],
      difficulty: 'beginner',
      lockedElementIds: ['color-block-1', 'color-block-2', 'color-block-3', 'white-panel'],
      editableElementIds: ['item-name', 'owner-name'],
    },
    backgroundColor: '#FFFFFF',
    elements: [
      // Color block 1
      createLockedElement<ShapeElement>({
        id: 'color-block-1',
        type: 'shape',
        shapeType: 'rectangle',
        x: 0,
        y: 0,
        width: 300,
        height: CANVAS_HEIGHT,
        rotation: 0,
        zIndex: 1,
        fill: '#FF6B6B',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Color block 2
      createLockedElement<ShapeElement>({
        id: 'color-block-2',
        type: 'shape',
        shapeType: 'rectangle',
        x: 300,
        y: 0,
        width: 300,
        height: CANVAS_HEIGHT,
        rotation: 0,
        zIndex: 1,
        fill: '#4ECDC4',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Color block 3
      createLockedElement<ShapeElement>({
        id: 'color-block-3',
        type: 'shape',
        shapeType: 'rectangle',
        x: 600,
        y: 0,
        width: 300,
        height: CANVAS_HEIGHT,
        rotation: 0,
        zIndex: 1,
        fill: '#FFE66D',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // White panel overlay
      createLockedElement<ShapeElement>({
        id: 'white-panel',
        type: 'shape',
        shapeType: 'rectangle',
        x: 60,
        y: 150,
        width: CANVAS_WIDTH - 120,
        height: 300,
        rotation: 0,
        zIndex: 2,
        fill: '#FFFFFF',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 15,
        locked: true,
        visible: true,
        opacity: 0.95,
      }),
      // Editable item name
      createEditableElement<TextElement>({
        id: 'item-name',
        type: 'text',
        content: 'CRAYONS',
        x: CANVAS_WIDTH / 2,
        y: 235,
        width: 650,
        height: 70,
        rotation: 0,
        zIndex: 10,
        fontSize: 56,
        fontFamily: 'Fredoka',
        fontWeight: 700,
        color: '#2C3E50',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 2,
        locked: false,
        visible: true,
        opacity: 1,
      }),
      // Editable owner name
      createEditableElement<TextElement>({
        id: 'owner-name',
        type: 'text',
        content: 'Liam Chen',
        x: CANVAS_WIDTH / 2,
        y: 340,
        width: 600,
        height: 60,
        rotation: 0,
        zIndex: 10,
        fontSize: 40,
        fontFamily: 'Poppins',
        fontWeight: 600,
        color: '#7F8C8D',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 0,
        locked: false,
        visible: true,
        opacity: 1,
      }),
    ],
  },

  // 4. Modern Minimalist School Label
  {
    metadata: {
      id: 'school-minimal',
      name: 'Minimalist School',
      description: 'Clean and modern school label',
      category: 'school',
      size: '3x2',
      tags: ['minimal', 'modern', 'clean', 'simple'],
      difficulty: 'beginner',
      lockedElementIds: ['side-accent', 'divider', 'dot-1', 'dot-2'],
      editableElementIds: ['student-label', 'class-label'],
    },
    backgroundColor: '#F8F9FA',
    elements: [
      // Side accent
      createLockedElement<ShapeElement>({
        id: 'side-accent',
        type: 'shape',
        shapeType: 'rectangle',
        x: 0,
        y: 0,
        width: 25,
        height: CANVAS_HEIGHT,
        rotation: 0,
        zIndex: 1,
        fill: '#9B59B6',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Divider
      createLockedElement<ShapeElement>({
        id: 'divider',
        type: 'shape',
        shapeType: 'rectangle',
        x: 100,
        y: 340,
        width: 700,
        height: 2,
        rotation: 0,
        zIndex: 2,
        fill: '#BDC3C7',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Dot 1
      createLockedElement<ShapeElement>({
        id: 'dot-1',
        type: 'shape',
        shapeType: 'circle',
        x: 65,
        y: 225,
        width: 20,
        height: 20,
        rotation: 0,
        zIndex: 3,
        fill: '#9B59B6',
        stroke: 'transparent',
        strokeWidth: 0,
        locked: true,
        visible: true,
        opacity: 0.5,
      }),
      // Dot 2
      createLockedElement<ShapeElement>({
        id: 'dot-2',
        type: 'shape',
        shapeType: 'circle',
        x: 65,
        y: 355,
        width: 20,
        height: 20,
        rotation: 0,
        zIndex: 3,
        fill: '#9B59B6',
        stroke: 'transparent',
        strokeWidth: 0,
        locked: true,
        visible: true,
        opacity: 0.5,
      }),
      // Editable student label
      createEditableElement<TextElement>({
        id: 'student-label',
        type: 'text',
        content: 'Noah Williams',
        x: 450,
        y: 210,
        width: 750,
        height: 80,
        rotation: 0,
        zIndex: 10,
        fontSize: 56,
        fontFamily: 'Montserrat',
        fontWeight: 700,
        color: '#2C3E50',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 0,
        locked: false,
        visible: true,
        opacity: 1,
      }),
      // Editable class label
      createEditableElement<TextElement>({
        id: 'class-label',
        type: 'text',
        content: 'Mrs. Anderson - Room 204',
        x: 450,
        y: 380,
        width: 750,
        height: 50,
        rotation: 0,
        zIndex: 10,
        fontSize: 32,
        fontFamily: 'Inter',
        fontWeight: 500,
        color: '#7F8C8D',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 0,
        locked: false,
        visible: true,
        opacity: 1,
      }),
    ],
  },

  // 5. Fun & Playful School Label
  {
    metadata: {
      id: 'school-playful',
      name: 'Fun & Playful',
      description: 'Playful design with geometric shapes',
      category: 'school',
      size: '3x2',
      tags: ['fun', 'playful', 'geometric', 'kid-friendly'],
      difficulty: 'beginner',
      lockedElementIds: ['bg-circle-1', 'bg-circle-2', 'bg-square', 'border-frame'],
      editableElementIds: ['name-big', 'subject-small'],
    },
    backgroundColor: '#FFF9F0',
    elements: [
      // Border frame
      createLockedElement<ShapeElement>({
        id: 'border-frame',
        type: 'shape',
        shapeType: 'rectangle',
        x: 25,
        y: 25,
        width: CANVAS_WIDTH - 50,
        height: CANVAS_HEIGHT - 50,
        rotation: 0,
        zIndex: 1,
        fill: 'transparent',
        stroke: '#E67E22',
        strokeWidth: 4,
        cornerRadius: 15,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Background circle 1
      createLockedElement<ShapeElement>({
        id: 'bg-circle-1',
        type: 'shape',
        shapeType: 'circle',
        x: 100,
        y: 100,
        width: 150,
        height: 150,
        rotation: 0,
        zIndex: 2,
        fill: '#3498DB',
        stroke: 'transparent',
        strokeWidth: 0,
        locked: true,
        visible: true,
        opacity: 0.15,
      }),
      // Background circle 2
      createLockedElement<ShapeElement>({
        id: 'bg-circle-2',
        type: 'shape',
        shapeType: 'circle',
        x: 650,
        y: 350,
        width: 120,
        height: 120,
        rotation: 0,
        zIndex: 2,
        fill: '#E74C3C',
        stroke: 'transparent',
        strokeWidth: 0,
        locked: true,
        visible: true,
        opacity: 0.15,
      }),
      // Background square
      createLockedElement<ShapeElement>({
        id: 'bg-square',
        type: 'shape',
        shapeType: 'rectangle',
        x: 700,
        y: 80,
        width: 130,
        height: 130,
        rotation: 25,
        zIndex: 2,
        fill: '#2ECC71',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 8,
        locked: true,
        visible: true,
        opacity: 0.15,
      }),
      // Editable big name
      createEditableElement<TextElement>({
        id: 'name-big',
        type: 'text',
        content: 'Ava Davis',
        x: CANVAS_WIDTH / 2,
        y: 230,
        width: 750,
        height: 90,
        rotation: 0,
        zIndex: 10,
        fontSize: 68,
        fontFamily: 'Fredoka',
        fontWeight: 700,
        color: '#E67E22',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 0,
        locked: false,
        visible: true,
        opacity: 1,
      }),
      // Editable subject
      createEditableElement<TextElement>({
        id: 'subject-small',
        type: 'text',
        content: 'SCIENCE',
        x: CANVAS_WIDTH / 2,
        y: 380,
        width: 600,
        height: 50,
        rotation: 0,
        zIndex: 10,
        fontSize: 36,
        fontFamily: 'Bebas Neue',
        fontWeight: 700,
        color: '#2C3E50',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 4,
        locked: false,
        visible: true,
        opacity: 1,
      }),
    ],
  },
]
