import { Template, createLockedElement, createEditableElement } from './enhanced-types'
import { TextElement, ShapeElement } from '@/types/designer'

// Spice Jar templates use 2" × 1" size (600 x 300 pixels)
const CANVAS_WIDTH = 600
const CANVAS_HEIGHT = 300

export const spiceJarTemplates: Template[] = [
  // 1. Classic Spice Label
  {
    metadata: {
      id: 'spice-classic',
      name: 'Classic Spice',
      description: 'Traditional spice jar label with clean border',
      category: 'spice-jar',
      size: '2x1',
      tags: ['classic', 'simple', 'clean', 'traditional'],
      difficulty: 'beginner',
      lockedElementIds: ['border-rect', 'accent-top', 'accent-bottom'],
      editableElementIds: ['spice-name'],
    },
    backgroundColor: '#FFFEF7',
    elements: [
      // Border rectangle
      createLockedElement<ShapeElement>({
        id: 'border-rect',
        type: 'shape',
        shapeType: 'rectangle',
        x: 15,
        y: 15,
        width: CANVAS_WIDTH - 30,
        height: CANVAS_HEIGHT - 30,
        rotation: 0,
        zIndex: 1,
        fill: 'transparent',
        stroke: '#8B4513',
        strokeWidth: 2,
        cornerRadius: 5,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Top accent line
      createLockedElement<ShapeElement>({
        id: 'accent-top',
        type: 'shape',
        shapeType: 'rectangle',
        x: 80,
        y: 100,
        width: CANVAS_WIDTH - 160,
        height: 1,
        rotation: 0,
        zIndex: 2,
        fill: '#CD853F',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Bottom accent line
      createLockedElement<ShapeElement>({
        id: 'accent-bottom',
        type: 'shape',
        shapeType: 'rectangle',
        x: 80,
        y: 199,
        width: CANVAS_WIDTH - 160,
        height: 1,
        rotation: 0,
        zIndex: 2,
        fill: '#CD853F',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Editable spice name
      createEditableElement<TextElement>({
        id: 'spice-name',
        type: 'text',
        content: 'BASIL',
        x: CANVAS_WIDTH / 2,
        y: 125,
        width: 400,
        height: 50,
        rotation: 0,
        zIndex: 10,
        fontSize: 42,
        fontFamily: 'Bebas Neue',
        fontWeight: 700,
        color: '#2C1810',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 3,
        locked: false,
        visible: true,
        opacity: 1,
      }),
    ],
  },

  // 2. Modern Minimal Spice
  {
    metadata: {
      id: 'spice-modern',
      name: 'Modern Minimal',
      description: 'Clean and contemporary spice label',
      category: 'spice-jar',
      size: '2x1',
      tags: ['modern', 'minimal', 'clean', 'simple'],
      difficulty: 'beginner',
      lockedElementIds: ['side-bar', 'dot-accent'],
      editableElementIds: ['spice-text'],
    },
    backgroundColor: '#FFFFFF',
    elements: [
      // Side color bar
      createLockedElement<ShapeElement>({
        id: 'side-bar',
        type: 'shape',
        shapeType: 'rectangle',
        x: 0,
        y: 0,
        width: 80,
        height: CANVAS_HEIGHT,
        rotation: 0,
        zIndex: 1,
        fill: '#E74C3C',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Dot accent
      createLockedElement<ShapeElement>({
        id: 'dot-accent',
        type: 'shape',
        shapeType: 'circle',
        x: 30,
        y: 125,
        width: 20,
        height: 20,
        rotation: 0,
        zIndex: 2,
        fill: '#FFFFFF',
        stroke: 'transparent',
        strokeWidth: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Editable spice text
      createEditableElement<TextElement>({
        id: 'spice-text',
        type: 'text',
        content: 'Paprika',
        x: 340,
        y: 120,
        width: 400,
        height: 60,
        rotation: 0,
        zIndex: 10,
        fontSize: 40,
        fontFamily: 'Montserrat',
        fontWeight: 600,
        color: '#2C3E50',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 1,
        locked: false,
        visible: true,
        opacity: 1,
      }),
    ],
  },

  // 3. Rustic Herb Label
  {
    metadata: {
      id: 'spice-rustic',
      name: 'Rustic Herb',
      description: 'Warm rustic design perfect for herbs',
      category: 'spice-jar',
      size: '2x1',
      tags: ['rustic', 'herb', 'warm', 'natural'],
      difficulty: 'beginner',
      lockedElementIds: ['bg-texture', 'corner-tl', 'corner-tr', 'corner-bl', 'corner-br'],
      editableElementIds: ['herb-name'],
    },
    backgroundColor: '#F4E4C1',
    elements: [
      // Background texture rectangle
      createLockedElement<ShapeElement>({
        id: 'bg-texture',
        type: 'shape',
        shapeType: 'rectangle',
        x: 30,
        y: 80,
        width: CANVAS_WIDTH - 60,
        height: 140,
        rotation: 0,
        zIndex: 1,
        fill: '#DEB887',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 8,
        locked: true,
        visible: true,
        opacity: 0.4,
      }),
      // Corner decorations
      createLockedElement<ShapeElement>({
        id: 'corner-tl',
        type: 'shape',
        shapeType: 'rectangle',
        x: 20,
        y: 20,
        width: 25,
        height: 3,
        rotation: 0,
        zIndex: 2,
        fill: '#8B7355',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      createLockedElement<ShapeElement>({
        id: 'corner-tr',
        type: 'shape',
        shapeType: 'rectangle',
        x: CANVAS_WIDTH - 45,
        y: 20,
        width: 25,
        height: 3,
        rotation: 0,
        zIndex: 2,
        fill: '#8B7355',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      createLockedElement<ShapeElement>({
        id: 'corner-bl',
        type: 'shape',
        shapeType: 'rectangle',
        x: 20,
        y: CANVAS_HEIGHT - 23,
        width: 25,
        height: 3,
        rotation: 0,
        zIndex: 2,
        fill: '#8B7355',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      createLockedElement<ShapeElement>({
        id: 'corner-br',
        type: 'shape',
        shapeType: 'rectangle',
        x: CANVAS_WIDTH - 45,
        y: CANVAS_HEIGHT - 23,
        width: 25,
        height: 3,
        rotation: 0,
        zIndex: 2,
        fill: '#8B7355',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Editable herb name
      createEditableElement<TextElement>({
        id: 'herb-name',
        type: 'text',
        content: 'Oregano',
        x: CANVAS_WIDTH / 2,
        y: 120,
        width: 450,
        height: 60,
        rotation: 0,
        zIndex: 10,
        fontSize: 44,
        fontFamily: 'Crimson Text',
        fontWeight: 600,
        color: '#5D4E37',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 1,
        fontStyle: 'italic',
        locked: false,
        visible: true,
        opacity: 1,
      }),
    ],
  },

  // 4. Vintage Apothecary Spice
  {
    metadata: {
      id: 'spice-vintage',
      name: 'Vintage Apothecary',
      description: 'Classic apothecary-style spice label',
      category: 'spice-jar',
      size: '2x1',
      tags: ['vintage', 'apothecary', 'classic', 'elegant'],
      difficulty: 'intermediate',
      lockedElementIds: ['banner-bg', 'frame-outer', 'flourish-left', 'flourish-right'],
      editableElementIds: ['spice-title'],
    },
    backgroundColor: '#E8DCC4',
    elements: [
      // Outer frame
      createLockedElement<ShapeElement>({
        id: 'frame-outer',
        type: 'shape',
        shapeType: 'rectangle',
        x: 10,
        y: 10,
        width: CANVAS_WIDTH - 20,
        height: CANVAS_HEIGHT - 20,
        rotation: 0,
        zIndex: 0,
        fill: 'transparent',
        stroke: '#6B5644',
        strokeWidth: 2,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Banner background
      createLockedElement<ShapeElement>({
        id: 'banner-bg',
        type: 'shape',
        shapeType: 'rectangle',
        x: 35,
        y: 95,
        width: CANVAS_WIDTH - 70,
        height: 110,
        rotation: 0,
        zIndex: 1,
        fill: '#2C1810',
        stroke: '#D4AF37',
        strokeWidth: 1,
        cornerRadius: 3,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Left flourish
      createLockedElement<ShapeElement>({
        id: 'flourish-left',
        type: 'shape',
        shapeType: 'circle',
        x: 45,
        y: 140,
        width: 10,
        height: 10,
        rotation: 0,
        zIndex: 2,
        fill: '#D4AF37',
        stroke: 'transparent',
        strokeWidth: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Right flourish
      createLockedElement<ShapeElement>({
        id: 'flourish-right',
        type: 'shape',
        shapeType: 'circle',
        x: CANVAS_WIDTH - 55,
        y: 140,
        width: 10,
        height: 10,
        rotation: 0,
        zIndex: 2,
        fill: '#D4AF37',
        stroke: 'transparent',
        strokeWidth: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Editable spice title
      createEditableElement<TextElement>({
        id: 'spice-title',
        type: 'text',
        content: 'CINNAMON',
        x: CANVAS_WIDTH / 2,
        y: 125,
        width: 400,
        height: 50,
        rotation: 0,
        zIndex: 10,
        fontSize: 36,
        fontFamily: 'Bebas Neue',
        fontWeight: 700,
        color: '#D4AF37',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 4,
        locked: false,
        visible: true,
        opacity: 1,
      }),
    ],
  },

  // 5. Fresh & Clean Spice
  {
    metadata: {
      id: 'spice-fresh',
      name: 'Fresh & Clean',
      description: 'Bright and fresh design with green accents',
      category: 'spice-jar',
      size: '2x1',
      tags: ['fresh', 'clean', 'bright', 'modern'],
      difficulty: 'beginner',
      lockedElementIds: ['top-stripe', 'bottom-stripe', 'circle-accent'],
      editableElementIds: ['name-text'],
    },
    backgroundColor: '#F5FFF5',
    elements: [
      // Top stripe
      createLockedElement<ShapeElement>({
        id: 'top-stripe',
        type: 'shape',
        shapeType: 'rectangle',
        x: 0,
        y: 0,
        width: CANVAS_WIDTH,
        height: 60,
        rotation: 0,
        zIndex: 1,
        fill: '#5C8A4D',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 0.2,
      }),
      // Bottom stripe
      createLockedElement<ShapeElement>({
        id: 'bottom-stripe',
        type: 'shape',
        shapeType: 'rectangle',
        x: 0,
        y: 240,
        width: CANVAS_WIDTH,
        height: 60,
        rotation: 0,
        zIndex: 1,
        fill: '#5C8A4D',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 0.2,
      }),
      // Circle accent
      createLockedElement<ShapeElement>({
        id: 'circle-accent',
        type: 'shape',
        shapeType: 'circle',
        x: CANVAS_WIDTH / 2 - 70,
        y: 80,
        width: 140,
        height: 140,
        rotation: 0,
        zIndex: 2,
        fill: 'transparent',
        stroke: '#5C8A4D',
        strokeWidth: 2,
        locked: true,
        visible: true,
        opacity: 0.3,
      }),
      // Editable name
      createEditableElement<TextElement>({
        id: 'name-text',
        type: 'text',
        content: 'Rosemary',
        x: CANVAS_WIDTH / 2,
        y: 125,
        width: 450,
        height: 50,
        rotation: 0,
        zIndex: 10,
        fontSize: 38,
        fontFamily: 'Poppins',
        fontWeight: 600,
        color: '#2D5016',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 1,
        locked: false,
        visible: true,
        opacity: 1,
      }),
    ],
  },
]
