import { Template, createLockedElement, createEditableElement } from './enhanced-types'
import { TextElement, ShapeElement } from '@/types/designer'

// Storage templates use 3" × 2" size (900 x 600 pixels)
const CANVAS_WIDTH = 900
const CANVAS_HEIGHT = 600

export const storageTemplates: Template[] = [
  // 1. Storage Bin Label
  {
    metadata: {
      id: 'storage-bin',
      name: 'Storage Bin Label',
      description: 'Versatile label for plastic storage containers',
      category: 'storage',
      size: '3x2',
      tags: ['storage', 'bins', 'organization', 'home'],
      difficulty: 'beginner',
      lockedElementIds: ['main-border', 'header-bar', 'category-box'],
      editableElementIds: ['contents-text', 'category-text', 'location-text'],
    },
    backgroundColor: '#F5F7FA',
    elements: [
      // Main border
      createLockedElement<ShapeElement>({
        id: 'main-border',
        type: 'shape',
        shapeType: 'rectangle',
        x: 20,
        y: 20,
        width: CANVAS_WIDTH - 40,
        height: CANVAS_HEIGHT - 40,
        rotation: 0,
        zIndex: 1,
        fill: 'transparent',
        stroke: '#34495E',
        strokeWidth: 4,
        cornerRadius: 10,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Header bar
      createLockedElement<ShapeElement>({
        id: 'header-bar',
        type: 'shape',
        shapeType: 'rectangle',
        x: 0,
        y: 0,
        width: CANVAS_WIDTH,
        height: 130,
        rotation: 0,
        zIndex: 2,
        fill: '#3498DB',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Category box
      createLockedElement<ShapeElement>({
        id: 'category-box',
        type: 'shape',
        shapeType: 'rectangle',
        x: 60,
        y: 420,
        width: CANVAS_WIDTH - 120,
        height: 120,
        rotation: 0,
        zIndex: 3,
        fill: '#ECF0F1',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 8,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Editable contents
      createEditableElement<TextElement>({
        id: 'contents-text',
        type: 'text',
        content: 'Holiday Decorations',
        x: CANVAS_WIDTH / 2,
        y: 50,
        width: 800,
        height: 70,
        rotation: 0,
        zIndex: 10,
        fontSize: 56,
        fontFamily: 'Poppins',
        fontWeight: 700,
        color: '#FFFFFF',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 0,
        locked: false,
        visible: true,
        opacity: 1,
      }),
      // Editable category
      createEditableElement<TextElement>({
        id: 'category-text',
        type: 'text',
        content: 'Christmas',
        x: CANVAS_WIDTH / 2,
        y: 210,
        width: 700,
        height: 120,
        rotation: 0,
        zIndex: 10,
        fontSize: 72,
        fontFamily: 'Montserrat',
        fontWeight: 700,
        color: '#2C3E50',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 1,
        locked: false,
        visible: true,
        opacity: 1,
      }),
      // Editable location
      createEditableElement<TextElement>({
        id: 'location-text',
        type: 'text',
        content: 'Basement - Shelf 3',
        x: CANVAS_WIDTH / 2,
        y: 460,
        width: 750,
        height: 60,
        rotation: 0,
        zIndex: 10,
        fontSize: 36,
        fontFamily: 'Inter',
        fontWeight: 600,
        color: '#7F8C8D',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 0,
        locked: false,
        visible: true,
        opacity: 1,
      }),
    ],
  },

  // 2. Garage Organization Label
  {
    metadata: {
      id: 'storage-garage',
      name: 'Garage Organization',
      description: 'Durable label for garage storage and tools',
      category: 'storage',
      size: '3x2',
      tags: ['garage', 'tools', 'workshop', 'organization'],
      difficulty: 'beginner',
      lockedElementIds: ['warning-stripe-1', 'warning-stripe-2', 'border-box'],
      editableElementIds: ['item-label', 'details-text'],
    },
    backgroundColor: '#2C3E50',
    elements: [
      // Border box
      createLockedElement<ShapeElement>({
        id: 'border-box',
        type: 'shape',
        shapeType: 'rectangle',
        x: 30,
        y: 30,
        width: CANVAS_WIDTH - 60,
        height: CANVAS_HEIGHT - 60,
        rotation: 0,
        zIndex: 1,
        fill: '#34495E',
        stroke: '#F39C12',
        strokeWidth: 4,
        cornerRadius: 8,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Warning stripe 1
      createLockedElement<ShapeElement>({
        id: 'warning-stripe-1',
        type: 'shape',
        shapeType: 'rectangle',
        x: 0,
        y: 0,
        width: CANVAS_WIDTH,
        height: 25,
        rotation: 0,
        zIndex: 2,
        fill: '#F39C12',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Warning stripe 2
      createLockedElement<ShapeElement>({
        id: 'warning-stripe-2',
        type: 'shape',
        shapeType: 'rectangle',
        x: 0,
        y: 575,
        width: CANVAS_WIDTH,
        height: 25,
        rotation: 0,
        zIndex: 2,
        fill: '#F39C12',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Editable item label
      createEditableElement<TextElement>({
        id: 'item-label',
        type: 'text',
        content: 'POWER TOOLS',
        x: CANVAS_WIDTH / 2,
        y: 215,
        width: 750,
        height: 100,
        rotation: 0,
        zIndex: 10,
        fontSize: 68,
        fontFamily: 'Bebas Neue',
        fontWeight: 700,
        color: '#F39C12',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 5,
        locked: false,
        visible: true,
        opacity: 1,
      }),
      // Editable details
      createEditableElement<TextElement>({
        id: 'details-text',
        type: 'text',
        content: 'Drills • Saws • Sanders',
        x: CANVAS_WIDTH / 2,
        y: 360,
        width: 700,
        height: 60,
        rotation: 0,
        zIndex: 10,
        fontSize: 32,
        fontFamily: 'Inter',
        fontWeight: 500,
        color: '#ECF0F1',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 1,
        locked: false,
        visible: true,
        opacity: 1,
      }),
    ],
  },

  // 3. Moving Box Label
  {
    metadata: {
      id: 'storage-moving',
      name: 'Moving Box Label',
      description: 'Comprehensive label for moving and packing',
      category: 'storage',
      size: '3x2',
      tags: ['moving', 'packing', 'relocation', 'organized'],
      difficulty: 'beginner',
      lockedElementIds: ['room-header', 'info-panel-1', 'info-panel-2', 'fragile-indicator'],
      editableElementIds: ['room-name', 'contents-list', 'fragile-text', 'box-number'],
    },
    backgroundColor: '#FFFFFF',
    elements: [
      // Room header
      createLockedElement<ShapeElement>({
        id: 'room-header',
        type: 'shape',
        shapeType: 'rectangle',
        x: 0,
        y: 0,
        width: CANVAS_WIDTH,
        height: 120,
        rotation: 0,
        zIndex: 1,
        fill: '#E67E22',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Info panel 1
      createLockedElement<ShapeElement>({
        id: 'info-panel-1',
        type: 'shape',
        shapeType: 'rectangle',
        x: 30,
        y: 150,
        width: 550,
        height: 280,
        rotation: 0,
        zIndex: 2,
        fill: '#F8F9FA',
        stroke: '#BDC3C7',
        strokeWidth: 2,
        cornerRadius: 8,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Info panel 2 (fragile indicator)
      createLockedElement<ShapeElement>({
        id: 'info-panel-2',
        type: 'shape',
        shapeType: 'rectangle',
        x: 610,
        y: 150,
        width: 260,
        height: 280,
        rotation: 0,
        zIndex: 2,
        fill: '#FEF5E7',
        stroke: '#F39C12',
        strokeWidth: 3,
        cornerRadius: 8,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Fragile indicator accent
      createLockedElement<ShapeElement>({
        id: 'fragile-indicator',
        type: 'shape',
        shapeType: 'rectangle',
        x: 610,
        y: 450,
        width: 260,
        height: 150,
        rotation: 0,
        zIndex: 3,
        fill: '#F39C12',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 0.2,
      }),
      // Editable room name
      createEditableElement<TextElement>({
        id: 'room-name',
        type: 'text',
        content: 'KITCHEN',
        x: CANVAS_WIDTH / 2,
        y: 40,
        width: 750,
        height: 70,
        rotation: 0,
        zIndex: 10,
        fontSize: 64,
        fontFamily: 'Bebas Neue',
        fontWeight: 700,
        color: '#FFFFFF',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 5,
        locked: false,
        visible: true,
        opacity: 1,
      }),
      // Editable contents
      createEditableElement<TextElement>({
        id: 'contents-list',
        type: 'text',
        content: 'Dishes\nGlassware\nSmall Appliances',
        x: 305,
        y: 230,
        width: 500,
        height: 180,
        rotation: 0,
        zIndex: 10,
        fontSize: 36,
        fontFamily: 'Inter',
        fontWeight: 600,
        color: '#2C3E50',
        textAlign: 'center',
        lineHeight: 1.4,
        letterSpacing: 0,
        locked: false,
        visible: true,
        opacity: 1,
      }),
      // Editable fragile text
      createEditableElement<TextElement>({
        id: 'fragile-text',
        type: 'text',
        content: 'FRAGILE\nHANDLE\nWITH CARE',
        x: 740,
        y: 235,
        width: 230,
        height: 170,
        rotation: 0,
        zIndex: 10,
        fontSize: 32,
        fontFamily: 'Bebas Neue',
        fontWeight: 700,
        color: '#E67E22',
        textAlign: 'center',
        lineHeight: 1.3,
        letterSpacing: 2,
        locked: false,
        visible: true,
        opacity: 1,
      }),
      // Editable box number
      createEditableElement<TextElement>({
        id: 'box-number',
        type: 'text',
        content: 'Box #12',
        x: 740,
        y: 500,
        width: 230,
        height: 50,
        rotation: 0,
        zIndex: 10,
        fontSize: 28,
        fontFamily: 'Inter',
        fontWeight: 700,
        color: '#E67E22',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 0,
        locked: false,
        visible: true,
        opacity: 1,
      }),
    ],
  },

  // 4. Seasonal Storage Label
  {
    metadata: {
      id: 'storage-seasonal',
      name: 'Seasonal Storage',
      description: 'Perfect for seasonal items and clothes',
      category: 'storage',
      size: '3x2',
      tags: ['seasonal', 'clothes', 'rotation', 'organized'],
      difficulty: 'beginner',
      lockedElementIds: ['season-icon-bg', 'divider-line', 'border-frame'],
      editableElementIds: ['season-text', 'items-text', 'year-text'],
    },
    backgroundColor: '#F0F8FF',
    elements: [
      // Border frame
      createLockedElement<ShapeElement>({
        id: 'border-frame',
        type: 'shape',
        shapeType: 'rectangle',
        x: 25,
        y: 25,
        width: CANVAS_WIDTH - 50,
        height: CANVAS_HEIGHT - 50,
        rotation: 0,
        zIndex: 1,
        fill: 'transparent',
        stroke: '#5DADE2',
        strokeWidth: 4,
        cornerRadius: 12,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Season icon background
      createLockedElement<ShapeElement>({
        id: 'season-icon-bg',
        type: 'shape',
        shapeType: 'circle',
        x: CANVAS_WIDTH / 2 - 100,
        y: 80,
        width: 200,
        height: 200,
        rotation: 0,
        zIndex: 2,
        fill: '#5DADE2',
        stroke: 'transparent',
        strokeWidth: 0,
        locked: true,
        visible: true,
        opacity: 0.2,
      }),
      // Divider line
      createLockedElement<ShapeElement>({
        id: 'divider-line',
        type: 'shape',
        shapeType: 'rectangle',
        x: 100,
        y: 340,
        width: CANVAS_WIDTH - 200,
        height: 2,
        rotation: 0,
        zIndex: 3,
        fill: '#5DADE2',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 0.4,
      }),
      // Editable season
      createEditableElement<TextElement>({
        id: 'season-text',
        type: 'text',
        content: 'WINTER',
        x: CANVAS_WIDTH / 2,
        y: 150,
        width: 700,
        height: 80,
        rotation: 0,
        zIndex: 10,
        fontSize: 72,
        fontFamily: 'Bebas Neue',
        fontWeight: 700,
        color: '#2874A6',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 8,
        locked: false,
        visible: true,
        opacity: 1,
      }),
      // Editable items
      createEditableElement<TextElement>({
        id: 'items-text',
        type: 'text',
        content: 'Sweaters • Coats • Boots',
        x: CANVAS_WIDTH / 2,
        y: 390,
        width: 750,
        height: 100,
        rotation: 0,
        zIndex: 10,
        fontSize: 38,
        fontFamily: 'Poppins',
        fontWeight: 600,
        color: '#34495E',
        textAlign: 'center',
        lineHeight: 1.3,
        letterSpacing: 0,
        locked: false,
        visible: true,
        opacity: 1,
      }),
      // Editable year
      createEditableElement<TextElement>({
        id: 'year-text',
        type: 'text',
        content: '2025-2026',
        x: CANVAS_WIDTH / 2,
        y: 510,
        width: 400,
        height: 40,
        rotation: 0,
        zIndex: 10,
        fontSize: 28,
        fontFamily: 'Inter',
        fontWeight: 500,
        color: '#7F8C8D',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 1,
        locked: false,
        visible: true,
        opacity: 1,
      }),
    ],
  },

  // 5. Archive Box Label
  {
    metadata: {
      id: 'storage-archive',
      name: 'Archive Box',
      description: 'Professional label for document storage and archives',
      category: 'storage',
      size: '3x2',
      tags: ['archive', 'documents', 'files', 'professional'],
      difficulty: 'beginner',
      lockedElementIds: ['header-stripe', 'field-box-1', 'field-box-2', 'field-box-3'],
      editableElementIds: ['category-title', 'description-text', 'date-range', 'box-id'],
    },
    backgroundColor: '#FDFEFE',
    elements: [
      // Header stripe
      createLockedElement<ShapeElement>({
        id: 'header-stripe',
        type: 'shape',
        shapeType: 'rectangle',
        x: 0,
        y: 0,
        width: CANVAS_WIDTH,
        height: 100,
        rotation: 0,
        zIndex: 1,
        fill: '#2C3E50',
        stroke: 'transparent',
        strokeWidth: 0,
        cornerRadius: 0,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Field box 1
      createLockedElement<ShapeElement>({
        id: 'field-box-1',
        type: 'shape',
        shapeType: 'rectangle',
        x: 40,
        y: 140,
        width: CANVAS_WIDTH - 80,
        height: 130,
        rotation: 0,
        zIndex: 2,
        fill: '#ECF0F1',
        stroke: '#BDC3C7',
        strokeWidth: 1,
        cornerRadius: 6,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Field box 2
      createLockedElement<ShapeElement>({
        id: 'field-box-2',
        type: 'shape',
        shapeType: 'rectangle',
        x: 40,
        y: 290,
        width: 550,
        height: 100,
        rotation: 0,
        zIndex: 2,
        fill: '#ECF0F1',
        stroke: '#BDC3C7',
        strokeWidth: 1,
        cornerRadius: 6,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Field box 3
      createLockedElement<ShapeElement>({
        id: 'field-box-3',
        type: 'shape',
        shapeType: 'rectangle',
        x: 610,
        y: 290,
        width: 250,
        height: 100,
        rotation: 0,
        zIndex: 2,
        fill: '#FEF9E7',
        stroke: '#F39C12',
        strokeWidth: 2,
        cornerRadius: 6,
        locked: true,
        visible: true,
        opacity: 1,
      }),
      // Editable category title
      createEditableElement<TextElement>({
        id: 'category-title',
        type: 'text',
        content: 'TAX RECORDS',
        x: CANVAS_WIDTH / 2,
        y: 35,
        width: 750,
        height: 60,
        rotation: 0,
        zIndex: 10,
        fontSize: 52,
        fontFamily: 'Bebas Neue',
        fontWeight: 700,
        color: '#ECF0F1',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 6,
        locked: false,
        visible: true,
        opacity: 1,
      }),
      // Editable description
      createEditableElement<TextElement>({
        id: 'description-text',
        type: 'text',
        content: 'Business Tax Returns\nReceipts & Invoices',
        x: CANVAS_WIDTH / 2,
        y: 165,
        width: 750,
        height: 95,
        rotation: 0,
        zIndex: 10,
        fontSize: 38,
        fontFamily: 'Inter',
        fontWeight: 600,
        color: '#2C3E50',
        textAlign: 'center',
        lineHeight: 1.3,
        letterSpacing: 0,
        locked: false,
        visible: true,
        opacity: 1,
      }),
      // Editable date range
      createEditableElement<TextElement>({
        id: 'date-range',
        type: 'text',
        content: '2020-2025',
        x: 315,
        y: 315,
        width: 500,
        height: 60,
        rotation: 0,
        zIndex: 10,
        fontSize: 42,
        fontFamily: 'Inter',
        fontWeight: 700,
        color: '#34495E',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 1,
        locked: false,
        visible: true,
        opacity: 1,
      }),
      // Editable box ID
      createEditableElement<TextElement>({
        id: 'box-id',
        type: 'text',
        content: 'BOX\nA-023',
        x: 735,
        y: 305,
        width: 220,
        height: 80,
        rotation: 0,
        zIndex: 10,
        fontSize: 32,
        fontFamily: 'Bebas Neue',
        fontWeight: 700,
        color: '#F39C12',
        textAlign: 'center',
        lineHeight: 1.2,
        letterSpacing: 2,
        locked: false,
        visible: true,
        opacity: 1,
      }),
    ],
  },
]
